#!/usr/bin/python
import code
import math
import cuts as ct
import ROOT as rt
from ROOT import TFile, TTree , TCanvas, TH1F, TList , TH2F ,TH3F ,TMath ,TF1, TStyle ,gStyle , TRefArray, TClonesArray, TObjArray, gPad, TPaveText, TLegend ,TString, TObject,gROOT,TFormula, TEllipse, TDirectory
from ROOT import TMath as mt
# this code creates the histograms from the analysis results and also applies some additional cuts 
# however I am still new to the pyroot so I might be defining histogram more than I needed 
# my goal was to create just one set of histogram and clear it after every time I store them in root file for different level of cuts
# Different directory are created to store all the histogram at different level of cuts


#Opening the file>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


file = TFile.Open("Incohernt_Phi_PID.root")
list = TList()
list = file.Get("UPCPhiTaskTest/UPCPhiWithTrigger")
tree = list.FindObject("scatterplot")
tree2 = file.Get("tree2")

#tree2.AddFriend(tree)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
text = TPaveText(.05,.1,.95,.8)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#this is to use to run in batch mode  to avoid printing all the plots
gROOT.SetBatch(rt.kTRUE)
#this create the master canvas color and the entries to print
#gStyle.SetCanvasColor(22)
gStyle.SetOptStat("e")

#master canvas
Master_Canvas = TCanvas("Master_Canvas","Master Canvas",600,300) # this is master canvas other will be cloned to this canvas
# master histograms here I will define the histograms 
  #master histograms for mass
fHistMass_Kaon = TH1F("fHistMass_Kaon","",100,0.8,2)
fHistMass_Kaon.SetXTitle("Mass of Parents(GeV/C^2)#rightarrow")
fHistMass_Kaon.SetYTitle("Number of Events #rightarrow")
fHistMass_Kaon.GetYaxis().SetTitleOffset(1.4)
fHistMass_Kaon.SetLineWidth(2)
fHistMass_Kaon.SetLineColor(rt.kBlue)
fHistMass_Pion = TH1F("fHistMass_Pion","",100,0,2)
fHistMass_Pion.GetYaxis().SetTitleOffset(1.4)
fHistMass_Pion.SetXTitle("Mass of Parents(GeV/C^2) #rightarrow")
fHistMass_Pion.SetYTitle("Number of Events #rightarrow")
fHistMass_Pion.SetLineWidth(2)
fHistMass_Pion.SetLineColor(rt.kBlue)
fHistMass_Electron = TH1F("fHistMass_Electron ","",100,0,2)
fHistMass_Electron.SetXTitle("Mass of Parents(GeV/C^2)")
fHistMass_Electron.GetYaxis().SetTitleOffset(1.4)
fHistMass_Electron.SetYTitle("Number of Events #rightarrow")
fHistMass_Electron.SetLineWidth(2)
fHistMass_Electron.SetLineColor(rt.kBlue)
  #master histogram for dedx
fHistdEdX = TH2F("fHistdEdX","",400,0,5,400,0,800)
fHistdEdX.SetXTitle("Momentum of Daughter Particle(P) #rightarrow")
fHistdEdX.SetYTitle("TPC dE/dX(arb unit) #rightarrow")
  #master histogram sigma vs sigma TPC/TOF
fHistSigmaVsSigma = TH2F("fHistSigmaVsSigma","",400,-20,20,400,-20,20)
fHistSigmaVsSigma.GetYaxis().SetTitleOffset(1.4)
  #master histogram sigma vs momentum
fHistSigmaVsP = TH2F("fHistSigmaVsP","",100,0,5,400,-20,20)
fHistSigmaVsP.GetYaxis().SetTitleOffset(1.4)
  #master histogram to compare two sigma
fHistSigma1VsSigma2 = TH2F("fHistSigma1VsSigma2","",400,-5,5,400,-10,10)
fHistSigma1VsSigma2.GetYaxis().SetTitleOffset(1.4)
 #master histogram phi 
fHistDelPhi = TH1F("fHistDelPhi","",100,0,5)
fHistDelPhi.GetYaxis().SetTitleOffset(1.4)

#tree2.Draw("fDelPhi2>>fHistDelPhi","","e")
#fHistDelPhi.Fit("pol1") 
phicanvas = Master_Canvas.Clone()
phicanvas.SetName("phicanvas")
phicanvas.cd()
func = TF1("func","pol2",0.5,1.5)
#func.SetParameter(0,1)
#func.SetParameter(1,50000)
#fHistDelPhi.Fit("func","RB") 
fHistDelPhi.SetDirectory(0)
func.SetLineColor(rt.kGreen)
func.Draw("SAME")

#this is where I start actually plotting
  # without cuts
    #mass
#file to fill the histograms after analysis
file2 = TFile("histograms_final_311.root","Recreate")
# directory is created to fill histograms without cuts
nocut = TDirectory() 
nocut = file2.mkdir("nocut")

nocut.cd()
Mass_0 = Master_Canvas.Clone()
Mass_0.SetName("Mass_")
fHistK = fHistMass_Kaon.Clone()
fHistK.SetName("fHistK")
Mass_0.cd()
tree.Draw("fM>>fHistK","","")
fHistK.SetDirectory(0)
Mass_0.Write()

Mass_1 = Master_Canvas.Clone()
Mass_1.SetName("Mass_1")
fHistPi = fHistMass_Pion.Clone()
fHistPi.SetName("fHistPi")
Mass_1.cd()
tree.Draw("fM>>fHistPi","","")
fHistPi.SetDirectory(0)
Mass_1.Write()
Mass_2 = Master_Canvas.Clone()
Mass_2.SetName("Mass_2")
fHistEl = fHistMass_Pion.Clone()
fHistEl.SetName("fHistEl")
Mass_2.cd()
tree.Draw("fM>>fHistEl","","")
fHistEl.SetDirectory(0)
Mass_2.Write()
    #sigmavsigma
Sigma_0 = Master_Canvas.Clone()
Sigma_0.SetName("Sigma_0")
fHistKSigma = fHistSigmaVsSigma.Clone()
fHistKSigma.SetName("fHistKSigma")
fHistKSigma.SetYTitle("N Sigma(Kaon Theory) Track 1 #rightarrow")
fHistKSigma.SetXTitle("N Sigma(Kaon Theory) Track 2#rightarrow")
Sigma_0.cd()
tree.Draw("fKaonSigma0:fKaonSigma1>>fHistKSigma","","COLZ")
fHistKSigma.SetDirectory(0)
Sigma_0.Write()

Sigma_1 = Master_Canvas.Clone()
Sigma_1.SetName("Sigma_1")
fHistPiSigma = fHistSigmaVsSigma.Clone()
fHistPiSigma.SetName("fHistPiSigma")
fHistPiSigma.SetYTitle("N Sigma(Pion Theory) Track 1 #rightarrow")
fHistPiSigma.SetXTitle("N Sigma(Pion Theory) Track 2#rightarrow")
Sigma_1.cd()
tree.Draw("fPiSigma0:fPiSigma1>>fHistPiSigma","","COLZ")
fHistPiSigma.SetDirectory(0)
Sigma_1.Write()
Sigma_2 = Master_Canvas.Clone()
Sigma_2.SetName("Sigma_2")
fHistElSigma = fHistSigmaVsSigma.Clone()
fHistElSigma.SetName("fHistElSigma")
fHistElSigma.SetYTitle("N Sigma(Electron Theory) Track 1 #rightarrow")
fHistElSigma.SetXTitle("N Sigma(Electron Theory) Track 2#rightarrow")
Sigma_2.cd()
tree.Draw("fElSigma0:fElSigma1>>fHistElSigma","","COLZ")
fHistElSigma.SetDirectory(0)
Sigma_1.Write()

    #sigmap
SigmaP1_0 = Master_Canvas.Clone()
SigmaP1_0.SetName("SigmaP1_0")
fHistKSigmaP1 = fHistSigmaVsP.Clone()
fHistKSigmaP1.SetName("fHistKSigmaP1")
fHistKSigmaP1.SetYTitle("N Sigma(Kaon Theory) Track 1 #rightarrow")
fHistKSigmaP1.SetXTitle("Momentum of the Track 1(GeV/C)#rightarrow")

fHistKSigmaP2 = fHistSigmaVsP.Clone()
fHistKSigmaP2.SetName("fHistKSigmaP2")
fHistKSigmaP2.SetYTitle("N Sigma(Kaon Theory) Track 2 #rightarrow")
fHistKSigmaP2.SetXTitle("Momentum of the Track 2(GeV/C)#rightarrow")
SigmaP1_0.Divide(2,1)
SigmaP1_0.cd(1)
tree.Draw("fKaonSigma0:fPd0>>fHistKSigmaP1","","COLZ")
fHistKSigmaP1.SetDirectory(0)
SigmaP1_0.cd(2)
tree.Draw("fKaonSigma1:fPd1>>fHistKSigmaP2","","COLZ")
fHistKSigmaP2.SetDirectory(0)
SigmaP1_0.Write()

SigmaP_1 = Master_Canvas.Clone()
SigmaP_1.SetName("SigmaP_1")
fHistPiSigmaP1 = fHistSigmaVsP.Clone()
fHistPiSigmaP1.SetName("fHistPiSigmaP1")
fHistPiSigmaP1.SetYTitle("N Sigma(Pion Theory) Track 1 #rightarrow")
fHistPiSigmaP1.SetXTitle("Momentum of the Track 1(GeV/C)#rightarrow")

fHistPiSigmaP2 = fHistSigmaVsP.Clone()
fHistPiSigmaP2.SetName("fHistPiSigmaP2")
fHistPiSigmaP2.SetYTitle("N Sigma(Pion Theory) Track 2 #rightarrow")
fHistPiSigmaP2.SetXTitle("Momentum of the Track 2(GeV/C)#rightarrow")

SigmaP_1.Divide(2,1)
SigmaP_1.cd(1)
tree.Draw("fPiSigma0:fPd0>>fHistPiSigmaP1","","COLZ")
fHistPiSigmaP1.SetDirectory(0)

SigmaP_1.cd(2)
tree.Draw("fPiSigma1:fPd1>>fHistPiSigmaP2","","COLZ")
fHistPiSigmaP2.SetDirectory(0)
SigmaP_1.Write()

SigmaP_2 = Master_Canvas.Clone()
SigmaP_2.SetName("SigmaP_2")
fHistElSigmaP1 = fHistSigmaVsP.Clone()
fHistElSigmaP1.SetName("fHistElSigmaP1")
fHistElSigmaP1.SetYTitle("N Sigma(Electron Theory) Track 1 #rightarrow")
fHistElSigmaP1.SetXTitle("Momentum of the Track 1(GeV/C)#rightarrow")

fHistElSigmaP2 = fHistSigmaVsP.Clone()
fHistElSigmaP2.SetName("fHistElSigmaP2")
fHistElSigmaP2.SetYTitle("N Sigma(Electron Theory) Track 2 #rightarrow")
fHistElSigmaP2.SetXTitle("Momentum of the Track 2(GeV/C)#rightarrow")
SigmaP_2.Divide(2,1)
SigmaP_2.cd(1)
tree.Draw("fElSigma0:fPd0>>fHistElSigmaP1","","COLZ")
fHistElSigmaP1.SetDirectory(0)   
SigmaP_2.cd(2)
tree.Draw("fElSigma1:fPd1>>fHistElSigmaP2","","COLZ")
fHistElSigmaP2.SetDirectory(0)
SigmaP_2.Write()

    #sigmaofkvs el or p
SigmaK_0 = Master_Canvas.Clone()
SigmaK_0.SetName("SigmaK_0")
fHistKSigmaVsPSigma1 = fHistSigma1VsSigma2.Clone()
fHistKSigmaVsPSigma1.SetName("fHistKSigmaVsPSigma1")
fHistKSigmaVsPSigma1.SetYTitle("N Sigma( Pion Theory) Track 1 #rightarrow")
fHistKSigmaVsPSigma1.SetXTitle("N Sigma(Kaon Theory) Track 1 #rightarrow")

fHistKSigmaVsPSigma2 = fHistSigma1VsSigma2.Clone()
fHistKSigmaVsPSigma2.SetName("fHistKSigmaVsPSigma2")
fHistKSigmaVsPSigma2.SetYTitle("N Sigma( Pion Theory) Track 2 #rightarrow")
fHistKSigmaVsPSigma2.SetXTitle("N Sigma(Kaon Theory) Track 2 #rightarrow")
SigmaK_0.Divide(2,1)
SigmaK_0.cd(1)  
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma1","","COLZ")
fHistKSigmaVsPSigma1.SetDirectory(0)
SigmaK_0.cd(2)  
tree.Draw("fPiSigma1:fKaonSigma1>>fHistKSigmaVsPSigma2","","COLZ")
fHistKSigmaVsPSigma2.SetDirectory(0)
SigmaK_0.Write()

SigmaK_1 = Master_Canvas.Clone()
SigmaK_1.SetName("SigmaK_1")
fHistKSigmaVsElSigma1 = fHistSigma1VsSigma2.Clone()
fHistKSigmaVsElSigma1.SetName("fHistKSigmaVsElSigma1")
fHistKSigmaVsElSigma1.SetYTitle("N Sigma( Electron Theory) Track 1 #rightarrow")
fHistKSigmaVsElSigma1.SetXTitle("N Sigma(Kaon Theory) Track 1 #rightarrow")

fHistKSigmaVsElSigma2 = fHistSigma1VsSigma2.Clone()
fHistKSigmaVsElSigma2.SetName("fHistKSigmaVsElSigma2")
fHistKSigmaVsElSigma2.SetYTitle("N Sigma( Electron Theory) Track 2 #rightarrow")
fHistKSigmaVsElSigma2.SetXTitle("N Sigma(Kaon Theory) Track 2 #rightarrow")
SigmaK_1.Divide(2,1)
SigmaK_1.cd(1)  
tree.Draw("fElSigma0:fKaonSigma0>>fHistKSigmaVsElSigma1","","COLZ")
fHistKSigmaVsElSigma1.SetDirectory(0)
SigmaK_1.cd(2)  
tree.Draw("fElSigma1:fKaonSigma1>>fHistKSigmaVsElSigma2","","COLZ")
fHistKSigmaVsElSigma2.SetDirectory(0)
SigmaK_1.Write()

SigmaTOF_0 = Master_Canvas.Clone()
SigmaTOF_0.SetName("SigmaTOF_0")
fHistKSigmaTOF = fHistSigmaVsSigma.Clone()
fHistKSigmaTOF.SetName("fHistKSigmaTOF")
fHistKSigmaTOF.SetYTitle("N TOF Sigma(Kaon Theory) Track 1 #rightarrow")
fHistKSigmaTOF.SetXTitle("N TOF Sigma(Kaon Theory) Track 2#rightarrow")
SigmaTOF_0.cd()
tree.Draw("fKaonSigmaTOF0:fKaonSigmaTOF1>>fHistKSigmaTOF","","COLZ")
fHistKSigmaTOF.SetDirectory(0)
SigmaTOF_0.Write()

SigmaTOF_1 = Master_Canvas.Clone()
SigmaTOF_1.SetName("SigmaTOF_1")
fHistPiSigmaTOF = fHistSigmaVsSigma.Clone()
fHistPiSigmaTOF.SetName("fHistPiSigmaTOF")
fHistPiSigmaTOF.SetYTitle("N TOF Sigma(Pion Theory) Track 1 #rightarrow")
fHistPiSigmaTOF.SetXTitle("N TOF Sigma(Pion Theory) Track 2#rightarrow")
SigmaTOF_1.cd()
tree.Draw("fPiSigmaTOF0:fPiSigmaTOF1>>fHistPiSigmaTOF","","COLZ")
fHistPiSigmaTOF.SetDirectory(0)
SigmaTOF_1.Write()

SigmaTOF_2 = Master_Canvas.Clone()
SigmaTOF_2.SetName("SigmaTOF_2")
fHistElSigmaTOF = fHistSigmaVsSigma.Clone()
fHistElSigmaTOF.SetName("fHistElSigmaTOF")
fHistElSigmaTOF.SetYTitle("N TOF Sigma(Electron Theory) Track 1 #rightarrow")
fHistElSigmaTOF.SetXTitle("N TOF Sigma(Electron Theory) Track 2#rightarrow")
SigmaTOF_2.cd()
tree.Draw("fElSigmaTOF0:fElSigmaTOF1>>fHistElSigmaTOF","","COLZ")
fHistElSigmaTOF.SetDirectory(0)
SigmaTOF_2.Write()

    #SigmaTOFp
SigmaTOFP1_0 = Master_Canvas.Clone()
SigmaTOFP1_0.SetName("SigmaTOFP1_0")
fHistKSigmaTOFP1 = fHistSigmaVsP.Clone()
fHistKSigmaTOFP1.SetName("fHistKSigmaTOFP1")
fHistKSigmaTOFP1.SetYTitle("N TOF Sigma(Kaon Theory) Track 1 #rightarrow")
fHistKSigmaTOFP1.SetXTitle("Momentum of the Track 1(GeV/C)#rightarrow")

fHistKSigmaTOFP2 = fHistSigmaVsP.Clone()
fHistKSigmaTOFP2.SetName("fHistKSigmaTOFP2")
fHistKSigmaTOFP2.SetYTitle("N TOF Sigma(Kaon Theory) Track 2 #rightarrow")
fHistKSigmaTOFP2.SetXTitle("Momentum of the Track 2(GeV/C)#rightarrow")
SigmaTOFP1_0.Divide(2,1)
SigmaTOFP1_0.cd(1)
tree.Draw("fKaonSigmaTOF0:fPd0>>fHistKSigmaTOFP1","","COLZ")
fHistKSigmaTOFP1.SetDirectory(0)
SigmaTOFP1_0.cd(2)
tree.Draw("fKaonSigmaTOF1:fPd1>>fHistKSigmaTOFP2","","COLZ")
fHistKSigmaTOFP2.SetDirectory(0)
SigmaTOFP1_0.Write()

SigmaTOFP_1 = Master_Canvas.Clone()
SigmaTOFP_1.SetName("SigmaTOFP_1")
fHistPiSigmaTOFP1 = fHistSigmaVsP.Clone()
fHistPiSigmaTOFP1.SetName("fHistPiSigmaTOFP1")
fHistPiSigmaTOFP1.SetYTitle("N TOF Sigma(Pion Theory) Track 1 #rightarrow")
fHistPiSigmaTOFP1.SetXTitle("Momentum of the Track 1(GeV/C)#rightarrow")

fHistPiSigmaTOFP2 = fHistSigmaVsP.Clone()
fHistPiSigmaTOFP2.SetName("fHistPiSigmaTOFP2")
fHistPiSigmaTOFP2.SetYTitle("N TOF Sigma(Pion Theory) Track 2 #rightarrow")
fHistPiSigmaTOFP2.SetXTitle("Momentum of the Track 2(GeV/C)#rightarrow")

SigmaTOFP_1.Divide(2,1)
SigmaTOFP_1.cd(1)
tree.Draw("fPiSigmaTOF0:fPd0>>fHistPiSigmaTOFP1","","COLZ")
fHistPiSigmaTOFP1.SetDirectory(0)

SigmaTOFP_1.cd(2)
tree.Draw("fPiSigmaTOF1:fPd1>>fHistPiSigmaTOFP2","","COLZ")
fHistPiSigmaTOFP2.SetDirectory(0)
SigmaTOFP_1.Write()

SigmaTOFP_2 = Master_Canvas.Clone()
SigmaTOFP_2.SetName("SigmaTOFP_2")
fHistElSigmaTOFP1 = fHistSigmaVsP.Clone()
fHistElSigmaTOFP1.SetName("fHistElSigmaTOFP1")
fHistElSigmaTOFP1.SetYTitle("N TOF Sigma(Electron Theory) Track 1 #rightarrow")
fHistElSigmaTOFP1.SetXTitle("Momentum of the Track 1(GeV/C)#rightarrow")

fHistElSigmaTOFP2 = fHistSigmaVsP.Clone()
fHistElSigmaTOFP2.SetName("fHistElSigmaTOFP2")
fHistElSigmaTOFP2.SetYTitle("N TOF Sigma(Electron Theory) Track 2 #rightarrow")
fHistElSigmaTOFP2.SetXTitle("Momentum of the Track 2(GeV/C)#rightarrow")
SigmaTOFP_2.Divide(2,1)
SigmaTOFP_2.cd(1)
tree.Draw("fElSigmaTOF0:fPd0>>fHistElSigmaTOFP1","","COLZ")
fHistElSigmaTOFP1.SetDirectory(0)   
SigmaTOFP_2.cd(2)
tree.Draw("fElSigmaTOF1:fPd1>>fHistElSigmaTOFP2","","COLZ")
fHistElSigmaTOFP2.SetDirectory(0)
SigmaTOFP_2.Write()

    #SigmaTOFofkvs el or p
SigmaTOFK_0 = Master_Canvas.Clone()
SigmaTOFK_0.SetName("SigmaTOFK_0")
fHistKSigmaTOFVsPSigmaTOF1 = fHistSigma1VsSigma2.Clone()
fHistKSigmaTOFVsPSigmaTOF1.SetName("fHistKSigmaTOFVsPSigmaTOF1")
fHistKSigmaTOFVsPSigmaTOF1.SetYTitle("N TOF Sigma( Pion Theory) Track 1 #rightarrow")
fHistKSigmaTOFVsPSigmaTOF1.SetXTitle("N TOF Sigma(Kaon Theory) Track 1 #rightarrow")

fHistKSigmaTOFVsPSigmaTOF2 = fHistSigma1VsSigma2.Clone()
fHistKSigmaTOFVsPSigmaTOF2.SetName("fHistKSigmaTOFVsPSigmaTOF2")
fHistKSigmaTOFVsPSigmaTOF2.SetYTitle("N TOF Sigma( Pion Theory) Track 2 #rightarrow")
fHistKSigmaTOFVsPSigmaTOF2.SetXTitle("N TOF Sigma(Kaon Theory) Track 2 #rightarrow")
SigmaTOFK_0.Divide(2,1)
SigmaTOFK_0.cd(1)  
tree.Draw("fPiSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsPSigmaTOF1","","COLZ")
fHistKSigmaTOFVsPSigmaTOF1.SetDirectory(0)
SigmaTOFK_0.cd(2)  
tree.Draw("fPiSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsPSigmaTOF2","","COLZ")
fHistKSigmaTOFVsPSigmaTOF2.SetDirectory(0)
SigmaTOFK_0.Write()

SigmaTOFK_1 = Master_Canvas.Clone()
SigmaTOFK_1.SetName("SigmaTOFK_1")
fHistKSigmaTOFVsElSigmaTOF1 = fHistSigma1VsSigma2.Clone()
fHistKSigmaTOFVsElSigmaTOF1.SetName("fHistKSigmaTOFVsElSigmaTOF1")
fHistKSigmaTOFVsElSigmaTOF1.SetYTitle("N TOF Sigma( Electron Theory) Track 1 #rightarrow")
fHistKSigmaTOFVsElSigmaTOF1.SetXTitle("N TOF Sigma(Kaon Theory) Track 1 #rightarrow")

fHistKSigmaTOFVsElSigmaTOF2 = fHistSigma1VsSigma2.Clone()
fHistKSigmaTOFVsElSigmaTOF2.SetName("fHistKSigmaTOFVsElSigmaTOF2")
fHistKSigmaTOFVsElSigmaTOF2.SetYTitle("N TOF Sigma( Electron Theory) Track 2 #rightarrow")
fHistKSigmaTOFVsElSigmaTOF2.SetXTitle("N TOF Sigma(Kaon Theory) Track 2 #rightarrow")
SigmaTOFK_1.Divide(2,1)
SigmaTOFK_1.cd(1)  
tree.Draw("fElSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsElSigmaTOF1","","COLZ")
fHistKSigmaTOFVsElSigmaTOF1.SetDirectory(0)
SigmaTOFK_1.cd(2)  
tree.Draw("fElSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsElSigmaTOF2","","COLZ")
fHistKSigmaTOFVsElSigmaTOF2.SetDirectory(0)
SigmaTOFK_1.Write()
###



elp = TEllipse(0,0,2,2)
elp.SetFillStyle(0)
elp.SetLineColor(rt.kRed)
elp.SetLineWidth(2)
gau = TF1("gau","gaus",-4,-10)
gau.SetLineWidth(3)
gau.SetLineColor(rt.kOrange)
gau2 = TF1("gau2","gaus",-2,0)
gau2.SetLineWidth(3)
gau2.SetLineColor(rt.kGreen)
gau3 = TF1("gau3","gaus(0)+gaus(3)",-12,2)
gau3.SetLineWidth(3)
#tree.Draw("fElSigma0:fKaonSigma0 >> tofsignal",ct.CombinedCut,"COLZ")
#tree.Draw("fPt1:fM >> tofsignal",ct.CombinedCut,"COLZ")

"""tofsignal.Fit("gau","NR")
tofsignal.Fit("gau2","NR+")
gau3.SetParameter(1,gau.GetParameter(1))
gau3.SetParameter(2,gau.GetParameter(2))
gau3.SetParameter(4,gau2.GetParameter(1))
gau3.SetParameter(5,gau2.GetParameter(2))
tofsignal.Fit("gau3","NR+")
r = gau3.GetChisquare()/gau3.GetNDF()
print "chisq and ndf " , r
gau4 = TF1("gau4","gaus",-12,2)
gau4.SetLineWidth(3)
gau4.SetLineColor(rt.kGreen)
gau4.FixParameter(0,gau.GetParameter(0))
gau4.FixParameter(1,gau.GetParameter(1))
gau4.FixParameter(2,gau.GetParameter(2))
gau4.Draw("SAME")
gau5 = TF1("gau5","gaus",-12,2)
gau5.SetLineWidth(3)
gau5.SetLineColor(rt.kOrange)
gau5.FixParameter(0,gau2.GetParameter(0))
gau5.FixParameter(1,gau2.GetParameter(1))
gau5.FixParameter(2,gau2.GetParameter(2))
gau5.Draw("SAME")
gau3.Draw("SAME")
#elp.Draw("SAME")
tofsignal2 =tofsignal.Clone()
#tofsignal2 = TH2F("tofsignal2","",300,0,2,300,0,300)
tofsignal2.SetName("tofsignal2")
#tofsignal2.SetLimits("")
tofsignal2.SetLineColor(rt.kRed)
tofsignal2.SetLineWidth(2)
#tofsignal2.SetXTitle("dEdX of Track 1 (As Kaon) #rightarrow")
#tofsignal2.SetXTitle("momentum of Track 1 (As Kaon) #rightarrow")
#tree.Draw("fKaonSigma0:fKaonSigma1 >> tofsignal2","((fPiSigma0-8)*(fPiSigma0-8)+(fPiSigma1-8)*(fPiSigma1-8))>25","COLZ")
tree.Draw("fM >> tofsignal2",ct.CombinedCut,"SAME")
tofsignal2.SetDirectory(0)
#canvas3.cd(3)
#tofsignal3 = TH1F("tofsignal3","",300,-20,20)
tofsignal3 =tofsignal.Clone()
tofsignal3.SetName("tofsignal3")
tofsignal3.SetLineColor(rt.kGreen)
tofsignal3.SetLineWidth(2)
tree.Draw("fElM>> tofsignal3",ct.TriggerCut+ct.n+"(fPiM>0.8 )","SAME")
tofsignal3.SetDirectory(0)
#canvas3.cd(4)
tofsignal4 =tofsignal.Clone()
#tofsignal4 = TH2F("tofsignal4","",300,-20,20,300,-20,20)
tofsignal4.SetName("tofsignal4")
tofsignal4.SetLineColor(rt.kBlack)
tofsignal4.SetLineWidth(2)
#tofsignal2.SetLimits("")
#tofsignal4.SetXTitle("dEdX of Track 1 (As Muon) #rightarrow")
#tofsignal4.SetXTitle("momentum of Track 1 (As Muon) #rightarrow")
#tree.Draw("fMuSigma0:fMuSigma1 >> tofsignal4","((fPiSigma0-8)*(fPiSigma0-8)+(fPiSigma1-8)*(fPiSigma1-8))<4","COLZ")
tree.Draw("fMuM>> tofsignal4",ct.TriggerCut,"SAME")

#tree.Draw("fdEdXTOF0/1000:fPd0 >> tofsignal4","","COLZ")
tofsignal4.SetDirectory(0)
canvas3.cd(5)
tofsignal5 =tofsignal.Clone()
tofsignal5.SetName("tofsignal5")
tree.Draw("fdEdXTOF0/1000:fPd0 >> tofsignal5","","COLZ")
tofsignal5.SetDirectory(0)
canvas3.cd(6)
tofsignal6 =tofsignal.Clone()
tofsignal6.SetName("tofsignal6")
tree.Draw("fdEdXTOF0/1000:fPd0 >> tofsignal6","","COLZ")
tofsignal6.SetDirectory(0)
canvas3.cd(7)
tofsignal7 =tofsignal.Clone()
tofsignal7.SetName("tofsignal7")
tree.Draw("fdEdXTOF0/1000:fPd0 >> tofsignal7","","COLZ")
tofsignal7.SetDirectory(0)
canvas3.cd(8)
tofsignal8 =tofsignal.Clone()
tofsignal8.SetName("tofsignal8")
tree.Draw("fdEdXTOF0/1000:fPd0 >> tofsignal8","","COLZ")
tofsignal8.SetDirectory(0)
canvas3.cd(9)

tofsignal9 =tofsignal.Clone()
tofsignal9.SetName("tofsignal9")
tree.Draw("fdEdXTOF0/1000:fPd0 >> tofsignal9","","COLZ")
tofsignal9.SetDirectory(0)

text.AddText("Cuts Applied Are")
text.AddText("CCUP8Trigger")
text.AddText("TwoTracksEvents")
text.AddText("Opposite Charge")
text.AddText("FilterBit 1>>0")
text.AddText("TPC cluster >60")
text.AddText("At least one Tracks P<0.5")"""
#setting margins


fHistK.Write()
fHistPi.Write()
fHistEl.Write()
fHistElSigma.Write()
fHistPiSigma.Write()
fHistKSigma.Write()
fHistElSigmaP1.Write()
fHistElSigmaP2.Write()
fHistKSigmaP1.Write()
fHistKSigmaP2.Write()
fHistPiSigmaP1.Write()
fHistPiSigmaP2.Write()
fHistKSigmaVsElSigma1.Write()
fHistKSigmaVsElSigma2.Write()
fHistKSigmaVsPSigma1.Write()
fHistKSigmaVsPSigma2.Write()
fHistDelPhi.Write()
fHistElSigmaTOF.Write()
fHistPiSigmaTOF.Write()
fHistKSigmaTOF.Write()
fHistElSigmaTOFP1.Write()
fHistElSigmaTOFP2.Write()
fHistKSigmaTOFP1.Write()
fHistKSigmaTOFP2.Write()
fHistPiSigmaTOFP1.Write()
fHistPiSigmaTOFP2.Write()
fHistKSigmaTOFVsElSigmaTOF1.Write()
fHistKSigmaTOFVsElSigmaTOF2.Write()
fHistKSigmaTOFVsPSigmaTOF1.Write()
fHistKSigmaTOFVsPSigmaTOF2.Write()


#dirname.cd("../") takes me out of the directory 
nocut.cd("../")
#histograms after triggercuts

triggercut = TDirectory()
triggercut = file2.mkdir("triggercut")
triggercut.cd()
TheCut = ct.TriggerCut
Mass_02 = Master_Canvas.Clone("Mass_02")
Mass_02.SetName("Mass_02")
fHistK2 = fHistK.Clone("fHistK2")
Mass_02.cd()
tree.Draw("fM>>fHistK2",TheCut,"e" )
fHistK2.SetDirectory(0)
fHistK2.Write()
Mass_02.Write()

Mass_12 = Master_Canvas.Clone("Mass_12")
Mass_12.SetName("Mass_12")
fHistPi2 = fHistPi.Clone("fHistPi2")
Mass_12.cd()
tree.Draw("fPiM>>fHistPi2",TheCut,"e" )
fHistPi2.SetDirectory(0)
fHistPi2.Write()
Mass_12.Write()

Mass_22 = Master_Canvas.Clone("Mass_22")
Mass_22.SetName("Mass_22")
fHistEl2 = fHistEl.Clone("fHistEl2")
Mass_22.cd()
tree.Draw("fElM>>fHistEl2",TheCut,"e" )
fHistEl2.SetDirectory(0)
fHistEl2.Write()
Mass_22.Write()

Sigma_22 = Master_Canvas.Clone("Sigma_22")
Sigma_22.SetName("Sigma_22")
fHistElSigma2 = fHistElSigma.Clone("fHistElSigma2")
Sigma_22.cd()
tree.Draw("fElSigma0:fElSigma1>>fHistElSigma2",TheCut,"COLZ")
fHistElSigma2.SetDirectory(0)
fHistElSigma2.Write()
Sigma_22.Write()

Sigma_12 = Master_Canvas.Clone("Sigma_12")
Sigma_12.SetName("Sigma_12")
fHistPiSigma2 = fHistPiSigma.Clone("fHistPiSigma2")
Sigma_12.cd()
tree.Draw("fPiSigma0:fPiSigma1>>fHistPiSigma2",TheCut,"COLZ" )
fHistPiSigma2.SetDirectory(0)
fHistPiSigma2.Write()
Sigma_12.Write()

Sigma_02 = Master_Canvas.Clone("Sigma_02")
Sigma_02.SetName("Sigma_02")
fHistKSigma2 = fHistKSigma.Clone("fHistKSigma2")
Sigma_02.cd()
tree.Draw("fKaonSigma0:fKaonSigma1>>fHistKSigma2",TheCut,"COLZ" )
fHistKSigma2.SetDirectory(0)
fHistKSigma2.Write()
Sigma_02.Write()

SigmaP_22 = Master_Canvas.Clone("SigmaP_22")
SigmaP_22.SetName("SigmaP_22")
SigmaP_22.Divide(2,1)
fHistElSigmaP12 = fHistElSigmaP1.Clone("fHistElSigmaP12")
SigmaP_22.cd(1)
tree.Draw("fElSigma0:fPd0>>fHistElSigmaP12",TheCut,"COLZ" )
fHistElSigmaP12.SetDirectory(0)
fHistElSigmaP12.Write()


fHistElSigmaP22 = fHistElSigmaP2.Clone("fHistElSigmaP22")
tree.Draw("fElSigma1:fPd1>>fHistElSigmaP22",TheCut,"COLZ" )
fHistElSigmaP22.SetDirectory(0)
fHistElSigmaP22.Write()
SigmaP_22.Write()

SigmaP1_02 = Master_Canvas.Clone("SigmaP1_02")
SigmaP1_02.SetName("SigmaP1_02")
SigmaP1_02.Divide(2,1)
fHistKSigmaP12 = fHistKSigmaP1.Clone("fHistKSigmaP12")
SigmaP1_02.cd(1)
tree.Draw("fKaonSigma0:fPd0>>fHistKSigmaP12",TheCut,"COLZ" )
fHistKSigmaP12.SetDirectory(0)
fHistKSigmaP12.Write()

SigmaP1_02.cd(2)
fHistKSigmaP22 = fHistKSigmaP2.Clone("fHistKSigmaP22")
tree.Draw("fKaonSigma1:fPd1>>fHistKSigmaP22",TheCut,"COLZ" )
fHistKSigmaP22.SetDirectory(0)
fHistKSigmaP22.Write()
SigmaP1_02.Write()

SigmaP_12 = Master_Canvas.Clone("SigmaP_12")
SigmaP_12.SetName("SigmaP_12")
SigmaP_12.Divide(2,1)
fHistPiSigmaP12 = fHistPiSigmaP1.Clone("fHistPiSigmaP12")
SigmaP_12.cd(1)
tree.Draw("fPiSigma0:fPd0>>fHistPiSigmaP12",TheCut,"COLZ" )
fHistPiSigmaP12.SetDirectory(0)
fHistPiSigmaP12.Write()

fHistPiSigmaP22 = fHistPiSigmaP2.Clone("fHistPiSigmaP22")
SigmaP_12.cd(2)
tree.Draw("fPiSigma1:fPd1>>fHistPiSigmaP22",TheCut,"COLZ" )
fHistPiSigmaP22.SetDirectory(0)
fHistPiSigmaP22.Write()
SigmaP_12.Write()

SigmaK_12 = Master_Canvas.Clone("SigmaK_12")
SigmaK_12.SetName("SigmaK_12")
SigmaK_12.Divide(2,1)
fHistKSigmaVsElSigma12 = fHistKSigmaVsElSigma1.Clone("fHistKSigmaVsElSigma12")
SigmaK_12.cd(1)
tree.Draw("fElSigma0:fKaonSigma0>>fHistKSigmaVsElSigma12",TheCut,"COLZ" )
fHistKSigmaVsElSigma12.SetDirectory(0)
fHistKSigmaVsElSigma12.Write()
fHistKSigmaVsElSigma22 = fHistKSigmaVsElSigma2.Clone("fHistKSigmaVsElSigma22")
SigmaK_12.cd(2)
tree.Draw("fElSigma1:fKaonSigma1>>fHistKSigmaVsElSigma22",TheCut,"COLZ" )
fHistKSigmaVsElSigma22.SetDirectory(0)
fHistKSigmaVsElSigma22.Write()
SigmaK_12.Write()

SigmaK_02 = Master_Canvas.Clone("SigmaK_02")
SigmaK_02.SetName("SigmaP_02")
SigmaK_02.Divide(2,1)
fHistKSigmaVsPSigma12 = fHistKSigmaVsPSigma1.Clone("fHistKSigmaVsPSigma12")
SigmaK_02.cd(1)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma12",TheCut,"COLZ" )
fHistKSigmaVsPSigma12.SetDirectory(0)
fHistKSigmaVsPSigma12.Write()


fHistKSigmaVsPSigma22 = fHistKSigmaVsPSigma2.Clone("fHistKSigmaVsPSigma22")
SigmaK_02.cd(2)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma22",TheCut,"COLZ")
fHistKSigmaVsPSigma22.SetDirectory(0)
fHistKSigmaVsPSigma22.Write()
SigmaK_02.Write()

SigmaTOF_02 = Master_Canvas.Clone("SigmaTOF_02")
SigmaTOF_02.SetName("SigmaTOF_02")
fHistKSigmaTOF2 = fHistKSigmaTOF.Clone("fHistKSigmaTOF2")
SigmaTOF_02.cd()
tree.Draw("fKaonSigmaTOF0:fKaonSigmaTOF1>>fHistKSigmaTOF2",TheCut,"COLZ")
fHistKSigmaTOF2.SetDirectory(0)
fHistKSigmaTOF2.Write()
SigmaTOF_02.Write()


SigmaTOF_12 = Master_Canvas.Clone("SigmaTOF_12")
SigmaTOF_12.SetName("SigmaTOF_12")
fHistPiSigmaTOF2 = fHistPiSigmaTOF.Clone("fHistPiSigmaTOF2")
SigmaTOF_12.cd()
tree.Draw("fPiSigmaTOF0:fPiSigmaTOF1>>fHistPiSigmaTOF2",TheCut,"COLZ")
fHistPiSigmaTOF2.SetDirectory(0)
fHistPiSigmaTOF2.Write()
SigmaTOF_12.Write()

SigmaTOF_22 = Master_Canvas.Clone("SigmaTOF_22")
SigmaTOF_22.SetName("SigmaTOF_22")
fHistElSigmaTOF2 = fHistElSigmaTOF.Clone("fHistElSigmaTOF2")
SigmaTOF_22.cd()
tree.Draw("fElSigmaTOF0:fElSigmaTOF1>>fHistElSigmaTOF2",TheCut,"COLZ")
fHistElSigmaTOF2.SetDirectory(0)
fHistElSigmaTOF2.Write()
SigmaTOF_22.Write()
    #SigmaTOFp
SigmaTOFP1_02 = Master_Canvas.Clone("SigmaTOFP1_02")
SigmaTOFP1_02.SetName("SigmaTOFP1_02")
fHistKSigmaTOFP12 = fHistKSigmaTOFP1.Clone("fHistKSigmaTOFP12")

fHistKSigmaTOFP22 = fHistKSigmaTOFP2.Clone("fHistKSigmaTOFP22")
fHistKSigmaTOFP22.SetName("fHistKSigmaTOFP22")

SigmaTOFP1_02.Divide(2,1)
SigmaTOFP1_02.cd(1)
tree.Draw("fKaonSigmaTOF0:fPd0>>fHistKSigmaTOFP12",TheCut,"COLZ")
fHistKSigmaTOFP12.SetDirectory(0)
SigmaTOFP1_02.cd(2)
tree.Draw("fKaonSigmaTOF1:fPd1>>fHistKSigmaTOFP22",TheCut,"COLZ")
fHistKSigmaTOFP22.SetDirectory(0)
fHistKSigmaTOFP12.Write()
fHistKSigmaTOFP22.Write()
SigmaTOFP1_02.Write()

SigmaTOFP_12 = Master_Canvas.Clone("SigmaTOFP_12")
SigmaTOFP_12.SetName("SigmaTOFP_12")
fHistPiSigmaTOFP12 = fHistPiSigmaTOFP1.Clone("fHistPiSigmaTOFP12")
fHistPiSigmaTOFP22 = fHistPiSigmaTOFP2.Clone("fHistPiSigmaTOFP22")
SigmaTOFP_12.Divide(2,1)
SigmaTOFP_12.cd(1)
tree.Draw("fPiSigmaTOF0:fPd0>>fHistPiSigmaTOFP12",TheCut,"COLZ")
fHistPiSigmaTOFP12.SetDirectory(0)

SigmaTOFP_12.cd(2)
tree.Draw("fPiSigmaTOF1:fPd1>>fHistPiSigmaTOFP22",TheCut,"COLZ")
fHistPiSigmaTOFP22.SetDirectory(0)
fHistPiSigmaTOFP12.Write()
fHistPiSigmaTOFP22.Write()
SigmaTOFP_12.Write()

SigmaTOFP_22 = Master_Canvas.Clone("SigmaTOFP_22")
SigmaTOFP_22.SetName("SigmaTOFP_22")
fHistElSigmaTOFP12 = fHistElSigmaTOFP1.Clone("fHistElSigmaTOFP12")
fHistElSigmaTOFP22 = fHistElSigmaTOFP2.Clone("fHistElSigmaTOFP22")

SigmaTOFP_22.Divide(2,1)
SigmaTOFP_22.cd(1)
tree.Draw("fElSigmaTOF0:fPd0>>fHistElSigmaTOFP12",TheCut,"COLZ")
fHistElSigmaTOFP12.SetDirectory(0)   
SigmaTOFP_22.cd(2)
tree.Draw("fElSigmaTOF1:fPd1>>fHistElSigmaTOFP22",TheCut,"COLZ")
fHistElSigmaTOFP22.SetDirectory(0)
fHistElSigmaTOFP12.Write()
fHistElSigmaTOFP22.Write()
SigmaTOFP_22.Write()

    #SigmaTOFof kaon vs el or p
SigmaTOFK_02 = Master_Canvas.Clone("SigmaTOFK_02")
SigmaTOFK_02.SetName("SigmaTOFK_02")
fHistKSigmaTOFVsPSigmaTOF12 = fHistKSigmaTOFVsPSigmaTOF1.Clone("fHistKSigmaTOFVsPSigmaTOF12")

fHistKSigmaTOFVsPSigmaTOF22 = fHistKSigmaTOFVsPSigmaTOF2.Clone("fHistKSigmaTOFVsPSigmaTOF22")
SigmaTOFK_02.Divide(2,1)
SigmaTOFK_02.cd(1)  
tree.Draw("fPiSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsPSigmaTOF12",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF12.SetDirectory(0)
SigmaTOFK_02.cd(2)  
tree.Draw("fPiSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsPSigmaTOF22",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF22.SetDirectory(0)
fHistKSigmaTOFVsPSigmaTOF12.Write()
fHistKSigmaTOFVsPSigmaTOF22.Write()
SigmaTOFK_02.Write()

SigmaTOFK_12 = Master_Canvas.Clone("SigmaTOFK_12")
SigmaTOFK_12.SetName("SigmaTOFK_12")
fHistKSigmaTOFVsElSigmaTOF12 = fHistKSigmaTOFVsElSigmaTOF1.Clone("fHistKSigmaTOFVsElSigmaTOF12")
fHistKSigmaTOFVsElSigmaTOF22 = fHistKSigmaTOFVsElSigmaTOF2.Clone("fHistKSigmaTOFVsElSigmaTOF22")

SigmaTOFK_12.Divide(2,1)
SigmaTOFK_12.cd(1)  
tree.Draw("fElSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsElSigmaTOF12",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF12.SetDirectory(0)
SigmaTOFK_12.cd(2)  
tree.Draw("fElSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsElSigmaTOF22",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF22.SetDirectory(0)
fHistKSigmaTOFVsElSigmaTOF12.Write()
fHistKSigmaTOFVsElSigmaTOF22.Write()
SigmaTOFK_12.Write()

#





triggercut.cd("../")
#histograms after the pisigma cut
picut = TDirectory()

picut = file2.mkdir("picut")
picut.cd()
TheCut = ct.TriggerCut+ct.n+ct.PiSigmaTPC_Cut
Mass_03 = Master_Canvas.Clone("Mass_03")
Mass_03.SetName("Mass_03")
fHistK3 = fHistK.Clone("fHistK3")
Mass_03.cd()
tree.Draw("fM>>fHistK3",TheCut,"e" )
fHistK3.SetDirectory(0)
fHistK3.Write()
Mass_03.Write()

Mass_13 = Master_Canvas.Clone("Mass_13")
Mass_13.SetName("Mass_13")
fHistPi3 = fHistPi.Clone("fHistPi3")
Mass_13.cd()
tree.Draw("fPiM>>fHistPi3",TheCut,"e" )
fHistPi3.SetDirectory(0)
fHistPi3.Write()
Mass_13.Write()

Mass_23 = Master_Canvas.Clone("Mass_23")
Mass_23.SetName("Mass_23")
fHistEl3 = fHistEl.Clone("fHistEl3")
Mass_23.cd()
tree.Draw("fElM>>fHistEl3",TheCut,"e" )
fHistEl3.SetDirectory(0)
fHistEl3.Write()
Mass_23.Write()

Sigma_23 = Master_Canvas.Clone("Sigma_23")
Sigma_23.SetName("Sigma_23")
fHistElSigma3 = fHistElSigma.Clone("fHistElSigma3")
Sigma_23.cd()
tree.Draw("fElSigma0:fElSigma1>>fHistElSigma3",TheCut,"COLZ")
fHistElSigma3.SetDirectory(0)
fHistElSigma3.Write()
Sigma_23.Write()

Sigma_13 = Master_Canvas.Clone("Sigma_13")
Sigma_13.SetName("Sigma_13")
fHistPiSigma3 = fHistPiSigma.Clone("fHistPiSigma3")
Sigma_13.cd()
tree.Draw("fPiSigma0:fPiSigma1>>fHistPiSigma3",TheCut,"COLZ" )
fHistPiSigma3.SetDirectory(0)
fHistPiSigma3.Write()
Sigma_13.Write()

Sigma_03 = Master_Canvas.Clone("Sigma_03")
Sigma_03.SetName("Sigma_03")
fHistKSigma3 = fHistKSigma.Clone("fHistKSigma3")
Sigma_03.cd()
tree.Draw("fKaonSigma0:fKaonSigma1>>fHistKSigma3",TheCut,"COLZ" )
fHistKSigma3.SetDirectory(0)
fHistKSigma3.Write()
Sigma_03.Write()

SigmaP_23 = Master_Canvas.Clone("SigmaP_23")
SigmaP_23.SetName("SigmaP_23")
SigmaP_23.Divide(2,1)
fHistElSigmaP13 = fHistElSigmaP1.Clone("fHistElSigmaP13")
SigmaP_23.cd(1)
tree.Draw("fElSigma0:fPd0>>fHistElSigmaP13",TheCut,"COLZ" )
fHistElSigmaP13.SetDirectory(0)
fHistElSigmaP13.Write()


fHistElSigmaP23 = fHistElSigmaP2.Clone("fHistElSigmaP23")
tree.Draw("fElSigma1:fPd1>>fHistElSigmaP23",TheCut,"COLZ" )
fHistElSigmaP23.SetDirectory(0)
fHistElSigmaP23.Write()
SigmaP_23.Write()

SigmaP1_03 = Master_Canvas.Clone("SigmaP1_03")
SigmaP1_03.SetName("SigmaP1_03")
SigmaP1_03.Divide(2,1)
fHistKSigmaP13 = fHistKSigmaP1.Clone("fHistKSigmaP13")
SigmaP1_03.cd(1)
tree.Draw("fKaonSigma0:fPd0>>fHistKSigmaP13",TheCut,"COLZ" )
fHistKSigmaP13.SetDirectory(0)
fHistKSigmaP13.Write()

SigmaP1_03.cd(2)
fHistKSigmaP23 = fHistKSigmaP2.Clone("fHistKSigmaP23")
tree.Draw("fKaonSigma1:fPd1>>fHistKSigmaP23",TheCut,"COLZ" )
fHistKSigmaP23.SetDirectory(0)
fHistKSigmaP23.Write()
SigmaP1_03.Write()

SigmaP_13 = Master_Canvas.Clone("SigmaP_13")
SigmaP_13.SetName("SigmaP_13")
SigmaP_13.Divide(2,1)
fHistPiSigmaP13 = fHistPiSigmaP1.Clone("fHistPiSigmaP13")
SigmaP_13.cd(1)
tree.Draw("fPiSigma0:fPd0>>fHistPiSigmaP13",TheCut,"COLZ" )
fHistPiSigmaP13.SetDirectory(0)
fHistPiSigmaP13.Write()

fHistPiSigmaP23 = fHistPiSigmaP2.Clone("fHistPiSigmaP23")
SigmaP_13.cd(2)
tree.Draw("fPiSigma1:fPd1>>fHistPiSigmaP23",TheCut,"COLZ" )
fHistPiSigmaP23.SetDirectory(0)
fHistPiSigmaP23.Write()
SigmaP_13.Write()

SigmaK_13 = Master_Canvas.Clone("SigmaK_13")
SigmaK_13.SetName("SigmaK_13")
SigmaK_13.Divide(2,1)
fHistKSigmaVsElSigma13 = fHistKSigmaVsElSigma1.Clone("fHistKSigmaVsElSigma13")
SigmaK_13.cd(1)
tree.Draw("fElSigma0:fKaonSigma0>>fHistKSigmaVsElSigma13",TheCut,"COLZ" )
fHistKSigmaVsElSigma13.SetDirectory(0)
fHistKSigmaVsElSigma13.Write()
fHistKSigmaVsElSigma23 = fHistKSigmaVsElSigma2.Clone("fHistKSigmaVsElSigma23")
SigmaK_13.cd(2)
tree.Draw("fElSigma1:fKaonSigma1>>fHistKSigmaVsElSigma23",TheCut,"COLZ" )
fHistKSigmaVsElSigma23.SetDirectory(0)
fHistKSigmaVsElSigma23.Write()
SigmaK_13.Write()

SigmaK_03 = Master_Canvas.Clone("SigmaK_03")
SigmaK_03.SetName("SigmaP_03")
SigmaK_03.Divide(2,1)
fHistKSigmaVsPSigma13 = fHistKSigmaVsPSigma1.Clone("fHistKSigmaVsPSigma13")
SigmaK_03.cd(1)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma13",TheCut,"COLZ" )
fHistKSigmaVsPSigma13.SetDirectory(0)
fHistKSigmaVsPSigma13.Write()


fHistKSigmaVsPSigma23 = fHistKSigmaVsPSigma2.Clone("fHistKSigmaVsPSigma23")
SigmaK_03.cd(2)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma23",TheCut,"COLZ")
fHistKSigmaVsPSigma23.SetDirectory(0)
fHistKSigmaVsPSigma23.Write()
SigmaK_03.Write()

TheCut = ct.TriggerCut + ct.n + ct.PiSigmaTOF_Cut
SigmaTOF_03 = Master_Canvas.Clone("SigmaTOF_03")
SigmaTOF_03.SetName("SigmaTOF_03")
fHistKSigmaTOF3 = fHistKSigmaTOF.Clone("fHistKSigmaTOF3")
SigmaTOF_03.cd()
tree.Draw("fKaonSigmaTOF0:fKaonSigmaTOF1>>fHistKSigmaTOF3",TheCut,"COLZ")
fHistKSigmaTOF3.SetDirectory(0)
fHistKSigmaTOF3.Write()
SigmaTOF_03.Write()


SigmaTOF_13 = Master_Canvas.Clone("SigmaTOF_13")
SigmaTOF_13.SetName("SigmaTOF_13")
fHistPiSigmaTOF3 = fHistPiSigmaTOF.Clone("fHistPiSigmaTOF3")
SigmaTOF_13.cd()
tree.Draw("fPiSigmaTOF0:fPiSigmaTOF1>>fHistPiSigmaTOF3",TheCut,"COLZ")
fHistPiSigmaTOF3.SetDirectory(0)
fHistPiSigmaTOF3.Write()
SigmaTOF_13.Write()

SigmaTOF_23 = Master_Canvas.Clone("SigmaTOF_23")
SigmaTOF_23.SetName("SigmaTOF_23")
fHistElSigmaTOF3 = fHistElSigmaTOF.Clone("fHistElSigmaTOF3")
SigmaTOF_23.cd()
tree.Draw("fElSigmaTOF0:fElSigmaTOF1>>fHistElSigmaTOF3",TheCut,"COLZ")
fHistElSigmaTOF3.SetDirectory(0)
fHistElSigmaTOF3.Write()
SigmaTOF_23.Write()
    #SigmaTOFp
SigmaTOFP1_03 = Master_Canvas.Clone("SigmaTOFP1_03")
SigmaTOFP1_03.SetName("SigmaTOFP1_03")
fHistKSigmaTOFP13 = fHistKSigmaTOFP1.Clone("fHistKSigmaTOFP13")

fHistKSigmaTOFP23 = fHistKSigmaTOFP2.Clone("fHistKSigmaTOFP23")
fHistKSigmaTOFP23.SetName("fHistKSigmaTOFP23")

SigmaTOFP1_03.Divide(2,1)
SigmaTOFP1_03.cd(1)
tree.Draw("fKaonSigmaTOF0:fPd0>>fHistKSigmaTOFP13",TheCut,"COLZ")
fHistKSigmaTOFP13.SetDirectory(0)
SigmaTOFP1_03.cd(2)
tree.Draw("fKaonSigmaTOF1:fPd1>>fHistKSigmaTOFP23",TheCut,"COLZ")
fHistKSigmaTOFP23.SetDirectory(0)
fHistKSigmaTOFP13.Write()
fHistKSigmaTOFP23.Write()
SigmaTOFP1_03.Write()

SigmaTOFP_13 = Master_Canvas.Clone("SigmaTOFP_13")
SigmaTOFP_13.SetName("SigmaTOFP_13")
fHistPiSigmaTOFP13 = fHistPiSigmaTOFP1.Clone("fHistPiSigmaTOFP13")
fHistPiSigmaTOFP23 = fHistPiSigmaTOFP2.Clone("fHistPiSigmaTOFP23")
SigmaTOFP_13.Divide(2,1)
SigmaTOFP_13.cd(1)
tree.Draw("fPiSigmaTOF0:fPd0>>fHistPiSigmaTOFP13",TheCut,"COLZ")
fHistPiSigmaTOFP13.SetDirectory(0)

SigmaTOFP_13.cd(2)
tree.Draw("fPiSigmaTOF1:fPd1>>fHistPiSigmaTOFP23",TheCut,"COLZ")
fHistPiSigmaTOFP23.SetDirectory(0)
fHistPiSigmaTOFP13.Write()
fHistPiSigmaTOFP23.Write()
SigmaTOFP_13.Write()

SigmaTOFP_23 = Master_Canvas.Clone("SigmaTOFP_23")
SigmaTOFP_23.SetName("SigmaTOFP_23")
fHistElSigmaTOFP13 = fHistElSigmaTOFP1.Clone("fHistElSigmaTOFP13")
fHistElSigmaTOFP23 = fHistElSigmaTOFP2.Clone("fHistElSigmaTOFP23")

SigmaTOFP_23.Divide(2,1)
SigmaTOFP_23.cd(1)
tree.Draw("fElSigmaTOF0:fPd0>>fHistElSigmaTOFP13",TheCut,"COLZ")
fHistElSigmaTOFP13.SetDirectory(0)   
SigmaTOFP_23.cd(2)
tree.Draw("fElSigmaTOF1:fPd1>>fHistElSigmaTOFP23",TheCut,"COLZ")
fHistElSigmaTOFP23.SetDirectory(0)
fHistElSigmaTOFP13.Write()
fHistElSigmaTOFP23.Write()
SigmaTOFP_23.Write()

    #SigmaTOFof kaon vs el or p
SigmaTOFK_03 = Master_Canvas.Clone("SigmaTOFK_03")
SigmaTOFK_03.SetName("SigmaTOFK_03")
fHistKSigmaTOFVsPSigmaTOF13 = fHistKSigmaTOFVsPSigmaTOF1.Clone("fHistKSigmaTOFVsPSigmaTOF13")

fHistKSigmaTOFVsPSigmaTOF23 = fHistKSigmaTOFVsPSigmaTOF2.Clone("fHistKSigmaTOFVsPSigmaTOF23")
SigmaTOFK_03.Divide(2,1)
SigmaTOFK_03.cd(1)  
tree.Draw("fPiSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsPSigmaTOF13",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF13.SetDirectory(0)
SigmaTOFK_03.cd(2)  
tree.Draw("fPiSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsPSigmaTOF23",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF23.SetDirectory(0)
fHistKSigmaTOFVsPSigmaTOF13.Write()
fHistKSigmaTOFVsPSigmaTOF23.Write()
SigmaTOFK_03.Write()

SigmaTOFK_13 = Master_Canvas.Clone("SigmaTOFK_13")
SigmaTOFK_13.SetName("SigmaTOFK_13")
fHistKSigmaTOFVsElSigmaTOF13 = fHistKSigmaTOFVsElSigmaTOF1.Clone("fHistKSigmaTOFVsElSigmaTOF13")
fHistKSigmaTOFVsElSigmaTOF23 = fHistKSigmaTOFVsElSigmaTOF2.Clone("fHistKSigmaTOFVsElSigmaTOF23")

SigmaTOFK_13.Divide(2,1)
SigmaTOFK_13.cd(1)  
tree.Draw("fElSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsElSigmaTOF13",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF13.SetDirectory(0)
SigmaTOFK_13.cd(2)  
tree.Draw("fElSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsElSigmaTOF23",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF23.SetDirectory(0)
fHistKSigmaTOFVsElSigmaTOF13.Write()
fHistKSigmaTOFVsElSigmaTOF23.Write()
SigmaTOFK_13.Write()

picut.cd("../")
#histograms after the el nsigma cut
elcut = TDirectory()
elcut = file2.mkdir("elcut")
elcut.cd()
TheCut = ct.TriggerCut + ct.n + ct.PiSigmaTPC_Cut+ct.n + ct.ElSigmaTPC_Cut
Mass_04 = Master_Canvas.Clone("Mass_04")
Mass_04.SetName("Mass_04")
fHistK4 = fHistK.Clone("fHistK4")
Mass_04.cd()
tree.Draw("fM>>fHistK4",TheCut,"e" )
fHistK4.SetDirectory(0)
fHistK4.Write()
Mass_04.Write()

Mass_14 = Master_Canvas.Clone("Mass_14")
Mass_14.SetName("Mass_14")
fHistPi4 = fHistPi.Clone("fHistPi4")
Mass_14.cd()
tree.Draw("fPiM>>fHistPi4",TheCut,"e" )
fHistPi4.SetDirectory(0)
fHistPi4.Write()
Mass_14.Write()

Mass_24 = Master_Canvas.Clone("Mass_24")
Mass_24.SetName("Mass_24")
fHistEl4 = fHistEl.Clone("fHistEl4")
Mass_24.cd()
tree.Draw("fElM>>fHistEl4",TheCut,"e" )
fHistEl4.SetDirectory(0)
fHistEl4.Write()
Mass_24.Write()

Sigma_24 = Master_Canvas.Clone("Sigma_24")
Sigma_24.SetName("Sigma_24")
fHistElSigma4 = fHistElSigma.Clone("fHistElSigma4")
Sigma_24.cd()
tree.Draw("fElSigma0:fElSigma1>>fHistElSigma4",TheCut,"COLZ")
fHistElSigma4.SetDirectory(0)
fHistElSigma4.Write()
Sigma_24.Write()

Sigma_14 = Master_Canvas.Clone("Sigma_14")
Sigma_14.SetName("Sigma_14")
fHistPiSigma4 = fHistPiSigma.Clone("fHistPiSigma4")
Sigma_14.cd()
tree.Draw("fPiSigma0:fPiSigma1>>fHistPiSigma4",TheCut,"COLZ" )
fHistPiSigma4.SetDirectory(0)
fHistPiSigma4.Write()
Sigma_14.Write()

Sigma_04 = Master_Canvas.Clone("Sigma_04")
Sigma_04.SetName("Sigma_04")
fHistKSigma4 = fHistKSigma.Clone("fHistKSigma4")
Sigma_04.cd()
tree.Draw("fKaonSigma0:fKaonSigma1>>fHistKSigma4",TheCut,"COLZ" )
fHistKSigma4.SetDirectory(0)
fHistKSigma4.Write()
Sigma_04.Write()

SigmaP_24 = Master_Canvas.Clone("SigmaP_24")
SigmaP_24.SetName("SigmaP_24")
SigmaP_24.Divide(2,1)
fHistElSigmaP14 = fHistElSigmaP1.Clone("fHistElSigmaP14")
SigmaP_24.cd(1)
tree.Draw("fElSigma0:fPd0>>fHistElSigmaP14",TheCut,"COLZ" )
fHistElSigmaP14.SetDirectory(0)
fHistElSigmaP14.Write()


fHistElSigmaP24 = fHistElSigmaP2.Clone("fHistElSigmaP24")
tree.Draw("fElSigma1:fPd1>>fHistElSigmaP24",TheCut,"COLZ" )
fHistElSigmaP24.SetDirectory(0)
fHistElSigmaP24.Write()
SigmaP_24.Write()

SigmaP1_04 = Master_Canvas.Clone("SigmaP1_04")
SigmaP1_04.SetName("SigmaP1_04")
SigmaP1_04.Divide(2,1)
fHistKSigmaP14 = fHistKSigmaP1.Clone("fHistKSigmaP14")
SigmaP1_04.cd(1)
tree.Draw("fKaonSigma0:fPd0>>fHistKSigmaP14",TheCut,"COLZ" )
fHistKSigmaP14.SetDirectory(0)
fHistKSigmaP14.Write()

SigmaP1_04.cd(2)
fHistKSigmaP24 = fHistKSigmaP2.Clone("fHistKSigmaP24")
tree.Draw("fKaonSigma1:fPd1>>fHistKSigmaP24",TheCut,"COLZ" )
fHistKSigmaP24.SetDirectory(0)
fHistKSigmaP24.Write()
SigmaP1_04.Write()

SigmaP_14 = Master_Canvas.Clone("SigmaP_14")
SigmaP_14.SetName("SigmaP_14")
SigmaP_14.Divide(2,1)
fHistPiSigmaP14 = fHistPiSigmaP1.Clone("fHistPiSigmaP14")
SigmaP_14.cd(1)
tree.Draw("fPiSigma0:fPd0>>fHistPiSigmaP14",TheCut,"COLZ" )
fHistPiSigmaP14.SetDirectory(0)
fHistPiSigmaP14.Write()

fHistPiSigmaP24 = fHistPiSigmaP2.Clone("fHistPiSigmaP24")
SigmaP_14.cd(2)
tree.Draw("fPiSigma1:fPd1>>fHistPiSigmaP24",TheCut,"COLZ" )
fHistPiSigmaP24.SetDirectory(0)
fHistPiSigmaP24.Write()
SigmaP_14.Write()

SigmaK_14 = Master_Canvas.Clone("SigmaK_14")
SigmaK_14.SetName("SigmaK_14")
SigmaK_14.Divide(2,1)
fHistKSigmaVsElSigma14 = fHistKSigmaVsElSigma1.Clone("fHistKSigmaVsElSigma14")
SigmaK_14.cd(1)
tree.Draw("fElSigma0:fKaonSigma0>>fHistKSigmaVsElSigma14",TheCut,"COLZ" )
fHistKSigmaVsElSigma14.SetDirectory(0)
fHistKSigmaVsElSigma14.Write()
fHistKSigmaVsElSigma24 = fHistKSigmaVsElSigma2.Clone("fHistKSigmaVsElSigma24")
SigmaK_14.cd(2)
tree.Draw("fElSigma1:fKaonSigma1>>fHistKSigmaVsElSigma24",TheCut,"COLZ" )
fHistKSigmaVsElSigma24.SetDirectory(0)
fHistKSigmaVsElSigma24.Write()
SigmaK_14.Write()

SigmaK_04 = Master_Canvas.Clone("SigmaK_04")
SigmaK_04.SetName("SigmaP_04")
SigmaK_04.Divide(2,1)
fHistKSigmaVsPSigma14 = fHistKSigmaVsPSigma1.Clone("fHistKSigmaVsPSigma14")
SigmaK_04.cd(1)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma14",TheCut,"COLZ" )
fHistKSigmaVsPSigma14.SetDirectory(0)
fHistKSigmaVsPSigma14.Write()


fHistKSigmaVsPSigma24 = fHistKSigmaVsPSigma2.Clone("fHistKSigmaVsPSigma24")
SigmaK_04.cd(2)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma24",TheCut,"COLZ")
fHistKSigmaVsPSigma24.SetDirectory(0)
fHistKSigmaVsPSigma24.Write()
SigmaK_04.Write()


TheCut = ct.TriggerCut+ct.n + ct.PiSigmaTOF_Cut+ct.n + ct.ElSigmaTOF_Cut
SigmaTOF_04 = Master_Canvas.Clone("SigmaTOF_04")
SigmaTOF_04.SetName("SigmaTOF_04")
fHistKSigmaTOF4 = fHistKSigmaTOF.Clone("fHistKSigmaTOF4")
SigmaTOF_04.cd()
tree.Draw("fKaonSigmaTOF0:fKaonSigmaTOF1>>fHistKSigmaTOF4",TheCut,"COLZ")
fHistKSigmaTOF4.SetDirectory(0)
fHistKSigmaTOF4.Write()
SigmaTOF_04.Write()


SigmaTOF_14 = Master_Canvas.Clone("SigmaTOF_14")
SigmaTOF_14.SetName("SigmaTOF_14")
fHistPiSigmaTOF4 = fHistPiSigmaTOF.Clone("fHistPiSigmaTOF4")
SigmaTOF_14.cd()
tree.Draw("fPiSigmaTOF0:fPiSigmaTOF1>>fHistPiSigmaTOF4",TheCut,"COLZ")
fHistPiSigmaTOF4.SetDirectory(0)
fHistPiSigmaTOF4.Write()
SigmaTOF_14.Write()

SigmaTOF_24 = Master_Canvas.Clone("SigmaTOF_24")
SigmaTOF_24.SetName("SigmaTOF_24")
fHistElSigmaTOF4 = fHistElSigmaTOF.Clone("fHistElSigmaTOF4")
SigmaTOF_24.cd()
tree.Draw("fElSigmaTOF0:fElSigmaTOF1>>fHistElSigmaTOF4",TheCut,"COLZ")
fHistElSigmaTOF4.SetDirectory(0)
fHistElSigmaTOF4.Write()
SigmaTOF_24.Write()
    #SigmaTOFp
SigmaTOFP1_04 = Master_Canvas.Clone("SigmaTOFP1_04")
SigmaTOFP1_04.SetName("SigmaTOFP1_04")
fHistKSigmaTOFP14 = fHistKSigmaTOFP1.Clone("fHistKSigmaTOFP14")

fHistKSigmaTOFP24 = fHistKSigmaTOFP2.Clone("fHistKSigmaTOFP24")
fHistKSigmaTOFP24.SetName("fHistKSigmaTOFP24")

SigmaTOFP1_04.Divide(2,1)
SigmaTOFP1_04.cd(1)
tree.Draw("fKaonSigmaTOF0:fPd0>>fHistKSigmaTOFP14",TheCut,"COLZ")
fHistKSigmaTOFP14.SetDirectory(0)
SigmaTOFP1_04.cd(2)
tree.Draw("fKaonSigmaTOF1:fPd1>>fHistKSigmaTOFP24",TheCut,"COLZ")
fHistKSigmaTOFP24.SetDirectory(0)
fHistKSigmaTOFP14.Write()
fHistKSigmaTOFP24.Write()
SigmaTOFP1_04.Write()

SigmaTOFP_14 = Master_Canvas.Clone("SigmaTOFP_14")
SigmaTOFP_14.SetName("SigmaTOFP_14")
fHistPiSigmaTOFP14 = fHistPiSigmaTOFP1.Clone("fHistPiSigmaTOFP14")
fHistPiSigmaTOFP24 = fHistPiSigmaTOFP2.Clone("fHistPiSigmaTOFP24")
SigmaTOFP_14.Divide(2,1)
SigmaTOFP_14.cd(1)
tree.Draw("fPiSigmaTOF0:fPd0>>fHistPiSigmaTOFP14",TheCut,"COLZ")
fHistPiSigmaTOFP14.SetDirectory(0)

SigmaTOFP_14.cd(2)
tree.Draw("fPiSigmaTOF1:fPd1>>fHistPiSigmaTOFP24",TheCut,"COLZ")
fHistPiSigmaTOFP24.SetDirectory(0)
fHistPiSigmaTOFP14.Write()
fHistPiSigmaTOFP24.Write()
SigmaTOFP_14.Write()

SigmaTOFP_24 = Master_Canvas.Clone("SigmaTOFP_24")
SigmaTOFP_24.SetName("SigmaTOFP_24")
fHistElSigmaTOFP14 = fHistElSigmaTOFP1.Clone("fHistElSigmaTOFP14")
fHistElSigmaTOFP24 = fHistElSigmaTOFP2.Clone("fHistElSigmaTOFP24")

SigmaTOFP_24.Divide(2,1)
SigmaTOFP_24.cd(1)
tree.Draw("fElSigmaTOF0:fPd0>>fHistElSigmaTOFP14",TheCut,"COLZ")
fHistElSigmaTOFP14.SetDirectory(0)   
SigmaTOFP_24.cd(2)
tree.Draw("fElSigmaTOF1:fPd1>>fHistElSigmaTOFP24",TheCut,"COLZ")
fHistElSigmaTOFP24.SetDirectory(0)
fHistElSigmaTOFP14.Write()
fHistElSigmaTOFP24.Write()
SigmaTOFP_24.Write()

    #SigmaTOFof kaon vs el or p
SigmaTOFK_04 = Master_Canvas.Clone("SigmaTOFK_04")
SigmaTOFK_04.SetName("SigmaTOFK_04")
fHistKSigmaTOFVsPSigmaTOF14 = fHistKSigmaTOFVsPSigmaTOF1.Clone("fHistKSigmaTOFVsPSigmaTOF14")

fHistKSigmaTOFVsPSigmaTOF24 = fHistKSigmaTOFVsPSigmaTOF2.Clone("fHistKSigmaTOFVsPSigmaTOF24")
SigmaTOFK_04.Divide(2,1)
SigmaTOFK_04.cd(1)  
tree.Draw("fPiSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsPSigmaTOF14",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF14.SetDirectory(0)
SigmaTOFK_04.cd(2)  
tree.Draw("fPiSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsPSigmaTOF24",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF24.SetDirectory(0)
fHistKSigmaTOFVsPSigmaTOF14.Write()
fHistKSigmaTOFVsPSigmaTOF24.Write()
SigmaTOFK_04.Write()

SigmaTOFK_14 = Master_Canvas.Clone("SigmaTOFK_14")
SigmaTOFK_14.SetName("SigmaTOFK_14")
fHistKSigmaTOFVsElSigmaTOF14 = fHistKSigmaTOFVsElSigmaTOF1.Clone("fHistKSigmaTOFVsElSigmaTOF14")
fHistKSigmaTOFVsElSigmaTOF24 = fHistKSigmaTOFVsElSigmaTOF2.Clone("fHistKSigmaTOFVsElSigmaTOF24")

SigmaTOFK_14.Divide(2,1)
SigmaTOFK_14.cd(1)  
tree.Draw("fElSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsElSigmaTOF14",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF14.SetDirectory(0)
SigmaTOFK_14.cd(2)  
tree.Draw("fElSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsElSigmaTOF24",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF24.SetDirectory(0)
fHistKSigmaTOFVsElSigmaTOF14.Write()
fHistKSigmaTOFVsElSigmaTOF24.Write()
SigmaTOFK_14.Write()



elcut.cd("../")
#histograms after the cut in transverse momentum
ptcut = TDirectory()
ptcut = file2.mkdir("ptcut")
ptcut.cd()
TheCut = ct.TriggerCut+ct.n + ct.PiSigmaTPC_Cut+ct.n+ct.ElSigmaTPC_Cut+ct.n+ ct.PtCut
Mass_05 = Master_Canvas.Clone("Mass_05")
Mass_05.SetName("Mass_05")
fHistK5 = fHistK.Clone("fHistK5")
Mass_05.cd()
tree.Draw("fM>>fHistK5",TheCut,"e" )
fHistK5.SetDirectory(0)
fHistK5.Write()
Mass_05.Write()

Mass_15 = Master_Canvas.Clone("Mass_15")
Mass_15.SetName("Mass_15")
fHistPi5 = fHistPi.Clone("fHistPi5")
Mass_15.cd()
tree.Draw("fPiM>>fHistPi5",TheCut,"e" )
fHistPi5.SetDirectory(0)
fHistPi5.Write()
Mass_15.Write()

Mass_25 = Master_Canvas.Clone("Mass_25")
Mass_25.SetName("Mass_25")
fHistEl5 = fHistEl.Clone("fHistEl5")
Mass_25.cd()
tree.Draw("fElM>>fHistEl5",TheCut,"e" )
fHistEl5.SetDirectory(0)
fHistEl5.Write()
Mass_25.Write()

Sigma_25 = Master_Canvas.Clone("Sigma_25")
Sigma_25.SetName("Sigma_25")
fHistElSigma5 = fHistElSigma.Clone("fHistElSigma5")
Sigma_25.cd()
tree.Draw("fElSigma0:fElSigma1>>fHistElSigma5",TheCut,"COLZ")
fHistElSigma5.SetDirectory(0)
fHistElSigma5.Write()
Sigma_25.Write()

Sigma_15 = Master_Canvas.Clone("Sigma_15")
Sigma_15.SetName("Sigma_15")
fHistPiSigma5 = fHistPiSigma.Clone("fHistPiSigma5")
Sigma_15.cd()
tree.Draw("fPiSigma0:fPiSigma1>>fHistPiSigma5",TheCut,"COLZ" )
fHistPiSigma5.SetDirectory(0)
fHistPiSigma5.Write()
Sigma_15.Write()

Sigma_05 = Master_Canvas.Clone("Sigma_05")
Sigma_05.SetName("Sigma_05")
fHistKSigma5 = fHistKSigma.Clone("fHistKSigma5")
Sigma_05.cd()
tree.Draw("fKaonSigma0:fKaonSigma1>>fHistKSigma5",TheCut,"COLZ" )
fHistKSigma5.SetDirectory(0)
fHistKSigma5.Write()
Sigma_05.Write()

SigmaP_25 = Master_Canvas.Clone("SigmaP_25")
SigmaP_25.SetName("SigmaP_25")
SigmaP_25.Divide(2,1)
fHistElSigmaP15 = fHistElSigmaP1.Clone("fHistElSigmaP15")
SigmaP_25.cd(1)
tree.Draw("fElSigma0:fPd0>>fHistElSigmaP15",TheCut,"COLZ" )
fHistElSigmaP15.SetDirectory(0)
fHistElSigmaP15.Write()


fHistElSigmaP25 = fHistElSigmaP2.Clone("fHistElSigmaP25")
tree.Draw("fElSigma1:fPd1>>fHistElSigmaP25",TheCut,"COLZ" )
fHistElSigmaP25.SetDirectory(0)
fHistElSigmaP25.Write()
SigmaP_25.Write()

SigmaP1_05 = Master_Canvas.Clone("SigmaP1_05")
SigmaP1_05.SetName("SigmaP1_05")
SigmaP1_05.Divide(2,1)
fHistKSigmaP15 = fHistKSigmaP1.Clone("fHistKSigmaP15")
SigmaP1_05.cd(1)
tree.Draw("fKaonSigma0:fPd0>>fHistKSigmaP15",TheCut,"COLZ" )
fHistKSigmaP15.SetDirectory(0)
fHistKSigmaP15.Write()

SigmaP1_05.cd(2)
fHistKSigmaP25 = fHistKSigmaP2.Clone("fHistKSigmaP25")
tree.Draw("fKaonSigma1:fPd1>>fHistKSigmaP25",TheCut,"COLZ" )
fHistKSigmaP25.SetDirectory(0)
fHistKSigmaP25.Write()
SigmaP1_05.Write()

SigmaP_15 = Master_Canvas.Clone("SigmaP_15")
SigmaP_15.SetName("SigmaP_15")
SigmaP_15.Divide(2,1)
fHistPiSigmaP15 = fHistPiSigmaP1.Clone("fHistPiSigmaP15")
SigmaP_15.cd(1)
tree.Draw("fPiSigma0:fPd0>>fHistPiSigmaP15",TheCut,"COLZ" )
fHistPiSigmaP15.SetDirectory(0)
fHistPiSigmaP15.Write()

fHistPiSigmaP25 = fHistPiSigmaP2.Clone("fHistPiSigmaP25")
SigmaP_15.cd(2)
tree.Draw("fPiSigma1:fPd1>>fHistPiSigmaP25",TheCut,"COLZ" )
fHistPiSigmaP25.SetDirectory(0)
fHistPiSigmaP25.Write()
SigmaP_15.Write()

SigmaK_15 = Master_Canvas.Clone("SigmaK_15")
SigmaK_15.SetName("SigmaK_15")
SigmaK_15.Divide(2,1)
fHistKSigmaVsElSigma15 = fHistKSigmaVsElSigma1.Clone("fHistKSigmaVsElSigma15")
SigmaK_15.cd(1)
tree.Draw("fElSigma0:fKaonSigma0>>fHistKSigmaVsElSigma15",TheCut,"COLZ" )
fHistKSigmaVsElSigma15.SetDirectory(0)
fHistKSigmaVsElSigma15.Write()
fHistKSigmaVsElSigma25 = fHistKSigmaVsElSigma2.Clone("fHistKSigmaVsElSigma25")
SigmaK_15.cd(2)
tree.Draw("fElSigma1:fKaonSigma1>>fHistKSigmaVsElSigma25",TheCut,"COLZ" )
fHistKSigmaVsElSigma25.SetDirectory(0)
fHistKSigmaVsElSigma25.Write()
SigmaK_15.Write()

SigmaK_05 = Master_Canvas.Clone("SigmaK_05")
SigmaK_05.SetName("SigmaP_05")
SigmaK_05.Divide(2,1)
fHistKSigmaVsPSigma15 = fHistKSigmaVsPSigma1.Clone("fHistKSigmaVsPSigma15")
SigmaK_05.cd(1)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma15",TheCut,"COLZ" )
fHistKSigmaVsPSigma15.SetDirectory(0)
fHistKSigmaVsPSigma15.Write()


fHistKSigmaVsPSigma25 = fHistKSigmaVsPSigma2.Clone("fHistKSigmaVsPSigma25")
SigmaK_05.cd(2)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma25",TheCut,"COLZ")
fHistKSigmaVsPSigma25.SetDirectory(0)
fHistKSigmaVsPSigma25.Write()
SigmaK_05.Write()

TheCut = ct.TriggerCut + ct.n +ct.PiSigmaTOF_Cut+ct.n+ct.ElSigmaTOF_Cut+ct.n+ct.PtCut
SigmaTOF_05 = Master_Canvas.Clone("SigmaTOF_05")
SigmaTOF_05.SetName("SigmaTOF_05")
fHistKSigmaTOF5 = fHistKSigmaTOF.Clone("fHistKSigmaTOF5")
SigmaTOF_05.cd()
tree.Draw("fKaonSigmaTOF0:fKaonSigmaTOF1>>fHistKSigmaTOF5",TheCut,"COLZ")
fHistKSigmaTOF5.SetDirectory(0)
fHistKSigmaTOF5.Write()
SigmaTOF_05.Write()


SigmaTOF_15 = Master_Canvas.Clone("SigmaTOF_15")
SigmaTOF_15.SetName("SigmaTOF_15")
fHistPiSigmaTOF5 = fHistPiSigmaTOF.Clone("fHistPiSigmaTOF5")
SigmaTOF_15.cd()
tree.Draw("fPiSigmaTOF0:fPiSigmaTOF1>>fHistPiSigmaTOF5",TheCut,"COLZ")
fHistPiSigmaTOF5.SetDirectory(0)
fHistPiSigmaTOF5.Write()
SigmaTOF_15.Write()

SigmaTOF_25 = Master_Canvas.Clone("SigmaTOF_25")
SigmaTOF_25.SetName("SigmaTOF_25")
fHistElSigmaTOF5 = fHistElSigmaTOF.Clone("fHistElSigmaTOF5")
SigmaTOF_25.cd()
tree.Draw("fElSigmaTOF0:fElSigmaTOF1>>fHistElSigmaTOF5",TheCut,"COLZ")
fHistElSigmaTOF5.SetDirectory(0)
fHistElSigmaTOF5.Write()
SigmaTOF_25.Write()
    #SigmaTOFp
SigmaTOFP1_05 = Master_Canvas.Clone("SigmaTOFP1_05")
SigmaTOFP1_05.SetName("SigmaTOFP1_05")
fHistKSigmaTOFP15 = fHistKSigmaTOFP1.Clone("fHistKSigmaTOFP15")

fHistKSigmaTOFP25 = fHistKSigmaTOFP2.Clone("fHistKSigmaTOFP25")
fHistKSigmaTOFP25.SetName("fHistKSigmaTOFP25")

SigmaTOFP1_05.Divide(2,1)
SigmaTOFP1_05.cd(1)
tree.Draw("fKaonSigmaTOF0:fPd0>>fHistKSigmaTOFP15",TheCut,"COLZ")
fHistKSigmaTOFP15.SetDirectory(0)
SigmaTOFP1_05.cd(2)
tree.Draw("fKaonSigmaTOF1:fPd1>>fHistKSigmaTOFP25",TheCut,"COLZ")
fHistKSigmaTOFP25.SetDirectory(0)
fHistKSigmaTOFP15.Write()
fHistKSigmaTOFP25.Write()
SigmaTOFP1_05.Write()

SigmaTOFP_15 = Master_Canvas.Clone("SigmaTOFP_15")
SigmaTOFP_15.SetName("SigmaTOFP_15")
fHistPiSigmaTOFP15 = fHistPiSigmaTOFP1.Clone("fHistPiSigmaTOFP15")
fHistPiSigmaTOFP25 = fHistPiSigmaTOFP2.Clone("fHistPiSigmaTOFP25")
SigmaTOFP_15.Divide(2,1)
SigmaTOFP_15.cd(1)
tree.Draw("fPiSigmaTOF0:fPd0>>fHistPiSigmaTOFP15",TheCut,"COLZ")
fHistPiSigmaTOFP15.SetDirectory(0)

SigmaTOFP_15.cd(2)
tree.Draw("fPiSigmaTOF1:fPd1>>fHistPiSigmaTOFP25",TheCut,"COLZ")
fHistPiSigmaTOFP25.SetDirectory(0)
fHistPiSigmaTOFP15.Write()
fHistPiSigmaTOFP25.Write()
SigmaTOFP_15.Write()

SigmaTOFP_25 = Master_Canvas.Clone("SigmaTOFP_25")
SigmaTOFP_25.SetName("SigmaTOFP_25")
fHistElSigmaTOFP15 = fHistElSigmaTOFP1.Clone("fHistElSigmaTOFP15")
fHistElSigmaTOFP25 = fHistElSigmaTOFP2.Clone("fHistElSigmaTOFP25")

SigmaTOFP_25.Divide(2,1)
SigmaTOFP_25.cd(1)
tree.Draw("fElSigmaTOF0:fPd0>>fHistElSigmaTOFP15",TheCut,"COLZ")
fHistElSigmaTOFP15.SetDirectory(0)   
SigmaTOFP_25.cd(2)
tree.Draw("fElSigmaTOF1:fPd1>>fHistElSigmaTOFP25",TheCut,"COLZ")
fHistElSigmaTOFP25.SetDirectory(0)
fHistElSigmaTOFP15.Write()
fHistElSigmaTOFP25.Write()
SigmaTOFP_25.Write()

    #SigmaTOFof kaon vs el or p
SigmaTOFK_05 = Master_Canvas.Clone("SigmaTOFK_05")
SigmaTOFK_05.SetName("SigmaTOFK_05")
fHistKSigmaTOFVsPSigmaTOF15 = fHistKSigmaTOFVsPSigmaTOF1.Clone("fHistKSigmaTOFVsPSigmaTOF15")

fHistKSigmaTOFVsPSigmaTOF25 = fHistKSigmaTOFVsPSigmaTOF2.Clone("fHistKSigmaTOFVsPSigmaTOF25")
SigmaTOFK_05.Divide(2,1)
SigmaTOFK_05.cd(1)  
tree.Draw("fPiSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsPSigmaTOF15",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF15.SetDirectory(0)
SigmaTOFK_05.cd(2)  
tree.Draw("fPiSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsPSigmaTOF25",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF25.SetDirectory(0)
fHistKSigmaTOFVsPSigmaTOF15.Write()
fHistKSigmaTOFVsPSigmaTOF25.Write()
SigmaTOFK_05.Write()

SigmaTOFK_15 = Master_Canvas.Clone("SigmaTOFK_15")
SigmaTOFK_15.SetName("SigmaTOFK_15")
fHistKSigmaTOFVsElSigmaTOF15 = fHistKSigmaTOFVsElSigmaTOF1.Clone("fHistKSigmaTOFVsElSigmaTOF15")
fHistKSigmaTOFVsElSigmaTOF25 = fHistKSigmaTOFVsElSigmaTOF2.Clone("fHistKSigmaTOFVsElSigmaTOF25")

SigmaTOFK_15.Divide(2,1)
SigmaTOFK_15.cd(1)  
tree.Draw("fElSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsElSigmaTOF15",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF15.SetDirectory(0)
SigmaTOFK_15.cd(2)  
tree.Draw("fElSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsElSigmaTOF25",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF25.SetDirectory(0)
fHistKSigmaTOFVsElSigmaTOF15.Write()
fHistKSigmaTOFVsElSigmaTOF25.Write()
SigmaTOFK_15.Write()


ptcut.cd("../")
#histogram after DCAxy cut
kaoncut = TDirectory()
kaoncut = file2.mkdir("kaoncut")
kaoncut.cd()
TheCut = ct.TriggerCut + ct.n +ct.PiSigmaTPC_Cut+ct.n+ct.ElSigmaTPC_Cut+ct.n+ct.PtCut +ct.n+ ct.KSigmaTPC_Cut
Mass_06 = Master_Canvas.Clone("Mass_06")
Mass_06.SetName("Mass_06")
fHistK6 = fHistK.Clone("fHistK6")
Mass_06.cd()
tree.Draw("fM>>fHistK6",TheCut,"e" )
fHistK6.SetDirectory(0)
fHistK6.Write()
Mass_06.Write()

Mass_16 = Master_Canvas.Clone("Mass_16")
Mass_16.SetName("Mass_16")
fHistPi6 = fHistPi.Clone("fHistPi6")
Mass_16.cd()
tree.Draw("fPiM>>fHistPi6",TheCut,"e" )
fHistPi6.SetDirectory(0)
fHistPi6.Write()
Mass_16.Write()

Mass_26 = Master_Canvas.Clone("Mass_26")
Mass_26.SetName("Mass_26")
fHistEl6 = fHistEl.Clone("fHistEl6")
Mass_26.cd()
tree.Draw("fElM>>fHistEl6",TheCut,"e" )
fHistEl6.SetDirectory(0)
fHistEl6.Write()
Mass_26.Write()

Sigma_26 = Master_Canvas.Clone("Sigma_26")
Sigma_26.SetName("Sigma_26")
fHistElSigma6 = fHistElSigma.Clone("fHistElSigma6")
Sigma_26.cd()
tree.Draw("fElSigma0:fElSigma1>>fHistElSigma6",TheCut,"COLZ")
fHistElSigma6.SetDirectory(0)
fHistElSigma6.Write()
Sigma_26.Write()

Sigma_16 = Master_Canvas.Clone("Sigma_16")
Sigma_16.SetName("Sigma_16")
fHistPiSigma6 = fHistPiSigma.Clone("fHistPiSigma6")
Sigma_16.cd()
tree.Draw("fPiSigma0:fPiSigma1>>fHistPiSigma6",TheCut,"COLZ" )
fHistPiSigma6.SetDirectory(0)
fHistPiSigma6.Write()
Sigma_16.Write()

Sigma_06 = Master_Canvas.Clone("Sigma_06")
Sigma_06.SetName("Sigma_06")
fHistKSigma6 = fHistKSigma.Clone("fHistKSigma6")
Sigma_06.cd()
tree.Draw("fKaonSigma0:fKaonSigma1>>fHistKSigma6",TheCut,"COLZ" )
fHistKSigma6.SetDirectory(0)
fHistKSigma6.Write()
Sigma_06.Write()

SigmaP_26 = Master_Canvas.Clone("SigmaP_26")
SigmaP_26.SetName("SigmaP_26")
SigmaP_26.Divide(2,1)
fHistElSigmaP16 = fHistElSigmaP1.Clone("fHistElSigmaP16")
SigmaP_26.cd(1)
tree.Draw("fElSigma0:fPd0>>fHistElSigmaP16",TheCut,"COLZ" )
fHistElSigmaP16.SetDirectory(0)
fHistElSigmaP16.Write()


fHistElSigmaP26 = fHistElSigmaP2.Clone("fHistElSigmaP26")
tree.Draw("fElSigma1:fPd1>>fHistElSigmaP26",TheCut,"COLZ" )
fHistElSigmaP26.SetDirectory(0)
fHistElSigmaP26.Write()
SigmaP_26.Write()

SigmaP1_06 = Master_Canvas.Clone("SigmaP1_06")
SigmaP1_06.SetName("SigmaP1_06")
SigmaP1_06.Divide(2,1)
fHistKSigmaP16 = fHistKSigmaP1.Clone("fHistKSigmaP16")
SigmaP1_06.cd(1)
tree.Draw("fKaonSigma0:fPd0>>fHistKSigmaP16",TheCut,"COLZ" )
fHistKSigmaP16.SetDirectory(0)
fHistKSigmaP16.Write()

SigmaP1_06.cd(2)
fHistKSigmaP26 = fHistKSigmaP2.Clone("fHistKSigmaP26")
tree.Draw("fKaonSigma1:fPd1>>fHistKSigmaP26",TheCut,"COLZ" )
fHistKSigmaP26.SetDirectory(0)
fHistKSigmaP26.Write()
SigmaP1_06.Write()

SigmaP_16 = Master_Canvas.Clone("SigmaP_16")
SigmaP_16.SetName("SigmaP_16")
SigmaP_16.Divide(2,1)
fHistPiSigmaP16 = fHistPiSigmaP1.Clone("fHistPiSigmaP16")
SigmaP_16.cd(1)
tree.Draw("fPiSigma0:fPd0>>fHistPiSigmaP16",TheCut,"COLZ" )
fHistPiSigmaP16.SetDirectory(0)
fHistPiSigmaP16.Write()

fHistPiSigmaP26 = fHistPiSigmaP2.Clone("fHistPiSigmaP26")
SigmaP_16.cd(2)
tree.Draw("fPiSigma1:fPd1>>fHistPiSigmaP26",TheCut,"COLZ" )
fHistPiSigmaP26.SetDirectory(0)
fHistPiSigmaP26.Write()
SigmaP_16.Write()

SigmaK_16 = Master_Canvas.Clone("SigmaK_16")
SigmaK_16.SetName("SigmaK_16")
SigmaK_16.Divide(2,1)
fHistKSigmaVsElSigma16 = fHistKSigmaVsElSigma1.Clone("fHistKSigmaVsElSigma16")
SigmaK_16.cd(1)
tree.Draw("fElSigma0:fKaonSigma0>>fHistKSigmaVsElSigma16",TheCut,"COLZ" )
fHistKSigmaVsElSigma16.SetDirectory(0)
fHistKSigmaVsElSigma16.Write()
fHistKSigmaVsElSigma26 = fHistKSigmaVsElSigma2.Clone("fHistKSigmaVsElSigma26")
SigmaK_16.cd(2)
tree.Draw("fElSigma1:fKaonSigma1>>fHistKSigmaVsElSigma26",TheCut,"COLZ" )
fHistKSigmaVsElSigma26.SetDirectory(0)
fHistKSigmaVsElSigma26.Write()
SigmaK_16.Write()

SigmaK_06 = Master_Canvas.Clone("SigmaK_06")
SigmaK_06.SetName("SigmaP_06")
SigmaK_06.Divide(2,1)
fHistKSigmaVsPSigma16 = fHistKSigmaVsPSigma1.Clone("fHistKSigmaVsPSigma16")
SigmaK_06.cd(1)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma16",TheCut,"COLZ" )
fHistKSigmaVsPSigma16.SetDirectory(0)
fHistKSigmaVsPSigma16.Write()


fHistKSigmaVsPSigma26 = fHistKSigmaVsPSigma2.Clone("fHistKSigmaVsPSigma26")
SigmaK_06.cd(2)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma26",TheCut,"COLZ")
fHistKSigmaVsPSigma26.SetDirectory(0)
fHistKSigmaVsPSigma26.Write()
SigmaK_06.Write()

TheCut = ct.TriggerCut + ct.n +ct.PiSigmaTOF_Cut+ct.n+ct.ElSigmaTOF_Cut+ct.n+ct.PtCut +ct.n+ ct.KSigmaTOF_Cut
SigmaTOF_06 = Master_Canvas.Clone("SigmaTOF_06")
SigmaTOF_06.SetName("SigmaTOF_06")
fHistKSigmaTOF6 = fHistKSigmaTOF.Clone("fHistKSigmaTOF6")
SigmaTOF_06.cd()
tree.Draw("fKaonSigmaTOF0:fKaonSigmaTOF1>>fHistKSigmaTOF6",TheCut,"COLZ")
fHistKSigmaTOF6.SetDirectory(0)
fHistKSigmaTOF6.Write()
SigmaTOF_06.Write()


SigmaTOF_16 = Master_Canvas.Clone("SigmaTOF_16")
SigmaTOF_16.SetName("SigmaTOF_16")
fHistPiSigmaTOF6 = fHistPiSigmaTOF.Clone("fHistPiSigmaTOF6")
SigmaTOF_16.cd()
tree.Draw("fPiSigmaTOF0:fPiSigmaTOF1>>fHistPiSigmaTOF6",TheCut,"COLZ")
fHistPiSigmaTOF6.SetDirectory(0)
fHistPiSigmaTOF6.Write()
SigmaTOF_16.Write()

SigmaTOF_26 = Master_Canvas.Clone("SigmaTOF_26")
SigmaTOF_26.SetName("SigmaTOF_26")
fHistElSigmaTOF6 = fHistElSigmaTOF.Clone("fHistElSigmaTOF6")
SigmaTOF_26.cd()
tree.Draw("fElSigmaTOF0:fElSigmaTOF1>>fHistElSigmaTOF6",TheCut,"COLZ")
fHistElSigmaTOF6.SetDirectory(0)
fHistElSigmaTOF6.Write()
SigmaTOF_26.Write()
    #SigmaTOFp
SigmaTOFP1_06 = Master_Canvas.Clone("SigmaTOFP1_06")
SigmaTOFP1_06.SetName("SigmaTOFP1_06")
fHistKSigmaTOFP16 = fHistKSigmaTOFP1.Clone("fHistKSigmaTOFP16")

fHistKSigmaTOFP26 = fHistKSigmaTOFP2.Clone("fHistKSigmaTOFP26")
fHistKSigmaTOFP26.SetName("fHistKSigmaTOFP26")

SigmaTOFP1_06.Divide(2,1)
SigmaTOFP1_06.cd(1)
tree.Draw("fKaonSigmaTOF0:fPd0>>fHistKSigmaTOFP16",TheCut,"COLZ")
fHistKSigmaTOFP16.SetDirectory(0)
SigmaTOFP1_06.cd(2)
tree.Draw("fKaonSigmaTOF1:fPd1>>fHistKSigmaTOFP26",TheCut,"COLZ")
fHistKSigmaTOFP26.SetDirectory(0)
fHistKSigmaTOFP16.Write()
fHistKSigmaTOFP26.Write()
SigmaTOFP1_06.Write()

SigmaTOFP_16 = Master_Canvas.Clone("SigmaTOFP_16")
SigmaTOFP_16.SetName("SigmaTOFP_16")
fHistPiSigmaTOFP16 = fHistPiSigmaTOFP1.Clone("fHistPiSigmaTOFP16")
fHistPiSigmaTOFP26 = fHistPiSigmaTOFP2.Clone("fHistPiSigmaTOFP26")
SigmaTOFP_16.Divide(2,1)
SigmaTOFP_16.cd(1)
tree.Draw("fPiSigmaTOF0:fPd0>>fHistPiSigmaTOFP16",TheCut,"COLZ")
fHistPiSigmaTOFP16.SetDirectory(0)

SigmaTOFP_16.cd(2)
tree.Draw("fPiSigmaTOF1:fPd1>>fHistPiSigmaTOFP26",TheCut,"COLZ")
fHistPiSigmaTOFP26.SetDirectory(0)
fHistPiSigmaTOFP16.Write()
fHistPiSigmaTOFP26.Write()
SigmaTOFP_16.Write()

SigmaTOFP_26 = Master_Canvas.Clone("SigmaTOFP_26")
SigmaTOFP_26.SetName("SigmaTOFP_26")
fHistElSigmaTOFP16 = fHistElSigmaTOFP1.Clone("fHistElSigmaTOFP16")
fHistElSigmaTOFP26 = fHistElSigmaTOFP2.Clone("fHistElSigmaTOFP26")

SigmaTOFP_26.Divide(2,1)
SigmaTOFP_26.cd(1)
tree.Draw("fElSigmaTOF0:fPd0>>fHistElSigmaTOFP16",TheCut,"COLZ")
fHistElSigmaTOFP16.SetDirectory(0)   
SigmaTOFP_26.cd(2)
tree.Draw("fElSigmaTOF1:fPd1>>fHistElSigmaTOFP26",TheCut,"COLZ")
fHistElSigmaTOFP26.SetDirectory(0)
fHistElSigmaTOFP16.Write()
fHistElSigmaTOFP26.Write()
SigmaTOFP_26.Write()

    #SigmaTOFof kaon vs el or p
SigmaTOFK_06 = Master_Canvas.Clone("SigmaTOFK_06")
SigmaTOFK_06.SetName("SigmaTOFK_06")
fHistKSigmaTOFVsPSigmaTOF16 = fHistKSigmaTOFVsPSigmaTOF1.Clone("fHistKSigmaTOFVsPSigmaTOF16")

fHistKSigmaTOFVsPSigmaTOF26 = fHistKSigmaTOFVsPSigmaTOF2.Clone("fHistKSigmaTOFVsPSigmaTOF26")
SigmaTOFK_06.Divide(2,1)
SigmaTOFK_06.cd(1)  
tree.Draw("fPiSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsPSigmaTOF16",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF16.SetDirectory(0)
SigmaTOFK_06.cd(2)  
tree.Draw("fPiSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsPSigmaTOF26",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF26.SetDirectory(0)
fHistKSigmaTOFVsPSigmaTOF16.Write()
fHistKSigmaTOFVsPSigmaTOF26.Write()
SigmaTOFK_06.Write()

SigmaTOFK_16 = Master_Canvas.Clone("SigmaTOFK_16")
SigmaTOFK_16.SetName("SigmaTOFK_16")
fHistKSigmaTOFVsElSigmaTOF16 = fHistKSigmaTOFVsElSigmaTOF1.Clone("fHistKSigmaTOFVsElSigmaTOF16")
fHistKSigmaTOFVsElSigmaTOF26 = fHistKSigmaTOFVsElSigmaTOF2.Clone("fHistKSigmaTOFVsElSigmaTOF26")

SigmaTOFK_16.Divide(2,1)
SigmaTOFK_16.cd(1)  
tree.Draw("fElSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsElSigmaTOF16",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF16.SetDirectory(0)
SigmaTOFK_16.cd(2)  
tree.Draw("fElSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsElSigmaTOF26",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF26.SetDirectory(0)
fHistKSigmaTOFVsElSigmaTOF16.Write()
fHistKSigmaTOFVsElSigmaTOF26.Write()
SigmaTOFK_16.Write()
kaoncut.cd("../")

finalcut = TDirectory()
finalcut = file2.mkdir("finalcut")
finalcut.cd()
TheCut = ct.CombinedCut
Mass_07 = Master_Canvas.Clone("Mass_07")
Mass_07.SetName("Mass_07")
fHistK7 = fHistK.Clone("fHistK7")
Mass_07.cd()
tree.Draw("fM>>fHistK7",TheCut,"e" )
fHistK7.SetDirectory(0)
fHistK7.Write()
Mass_07.Write()

Mass_17 = Master_Canvas.Clone("Mass_17")
Mass_17.SetName("Mass_17")
fHistPi7 = fHistPi.Clone("fHistPi7")
Mass_17.cd()
tree.Draw("fPiM>>fHistPi7",TheCut,"e" )
fHistPi7.SetDirectory(0)
fHistPi7.Write()
Mass_17.Write()

Mass_27 = Master_Canvas.Clone("Mass_27")
Mass_27.SetName("Mass_27")
fHistEl7 = fHistEl.Clone("fHistEl7")
Mass_27.cd()
tree.Draw("fElM>>fHistEl7",TheCut,"e" )
fHistEl7.SetDirectory(0)
fHistEl7.Write()
Mass_27.Write()

Sigma_27 = Master_Canvas.Clone("Sigma_27")
Sigma_27.SetName("Sigma_27")
fHistElSigma7 = fHistElSigma.Clone("fHistElSigma7")
Sigma_27.cd()
tree.Draw("fElSigma0:fElSigma1>>fHistElSigma7",TheCut,"COLZ")
fHistElSigma7.SetDirectory(0)
fHistElSigma7.Write()
Sigma_27.Write()

Sigma_17 = Master_Canvas.Clone("Sigma_17")
Sigma_17.SetName("Sigma_17")
fHistPiSigma7 = fHistPiSigma.Clone("fHistPiSigma7")
Sigma_17.cd()
tree.Draw("fPiSigma0:fPiSigma1>>fHistPiSigma7",TheCut,"COLZ" )
fHistPiSigma7.SetDirectory(0)
fHistPiSigma7.Write()
Sigma_17.Write()

Sigma_07 = Master_Canvas.Clone("Sigma_07")
Sigma_07.SetName("Sigma_07")
fHistKSigma7 = fHistKSigma.Clone("fHistKSigma7")
Sigma_07.cd()
tree.Draw("fKaonSigma0:fKaonSigma1>>fHistKSigma7",TheCut,"COLZ" )
fHistKSigma7.SetDirectory(0)
fHistKSigma7.Write()
Sigma_07.Write()

SigmaP_27 = Master_Canvas.Clone("SigmaP_27")
SigmaP_27.SetName("SigmaP_27")
SigmaP_27.Divide(2,1)
fHistElSigmaP17 = fHistElSigmaP1.Clone("fHistElSigmaP17")
SigmaP_27.cd(1)
tree.Draw("fElSigma0:fPd0>>fHistElSigmaP17",TheCut,"COLZ" )
fHistElSigmaP17.SetDirectory(0)
fHistElSigmaP17.Write()


fHistElSigmaP27 = fHistElSigmaP2.Clone("fHistElSigmaP27")
tree.Draw("fElSigma1:fPd1>>fHistElSigmaP27",TheCut,"COLZ" )
fHistElSigmaP27.SetDirectory(0)
fHistElSigmaP27.Write()
SigmaP_27.Write()

SigmaP1_07 = Master_Canvas.Clone("SigmaP1_07")
SigmaP1_07.SetName("SigmaP1_07")
SigmaP1_07.Divide(2,1)
fHistKSigmaP17 = fHistKSigmaP1.Clone("fHistKSigmaP17")
SigmaP1_07.cd(1)
tree.Draw("fKaonSigma0:fPd0>>fHistKSigmaP17",TheCut,"COLZ" )
fHistKSigmaP17.SetDirectory(0)
fHistKSigmaP17.Write()

SigmaP1_07.cd(2)
fHistKSigmaP27 = fHistKSigmaP2.Clone("fHistKSigmaP27")
tree.Draw("fKaonSigma1:fPd1>>fHistKSigmaP27",TheCut,"COLZ" )
fHistKSigmaP27.SetDirectory(0)
fHistKSigmaP27.Write()
SigmaP1_07.Write()

SigmaP_17 = Master_Canvas.Clone("SigmaP_17")
SigmaP_17.SetName("SigmaP_17")
SigmaP_17.Divide(2,1)
fHistPiSigmaP17 = fHistPiSigmaP1.Clone("fHistPiSigmaP17")
SigmaP_17.cd(1)
tree.Draw("fPiSigma0:fPd0>>fHistPiSigmaP17",TheCut,"COLZ" )
fHistPiSigmaP17.SetDirectory(0)
fHistPiSigmaP17.Write()

fHistPiSigmaP27 = fHistPiSigmaP2.Clone("fHistPiSigmaP27")
SigmaP_17.cd(2)
tree.Draw("fPiSigma1:fPd1>>fHistPiSigmaP27",TheCut,"COLZ" )
fHistPiSigmaP27.SetDirectory(0)
fHistPiSigmaP27.Write()
SigmaP_17.Write()

SigmaK_17 = Master_Canvas.Clone("SigmaK_17")
SigmaK_17.SetName("SigmaK_17")
SigmaK_17.Divide(2,1)
fHistKSigmaVsElSigma17 = fHistKSigmaVsElSigma1.Clone("fHistKSigmaVsElSigma17")
SigmaK_17.cd(1)
tree.Draw("fElSigma0:fKaonSigma0>>fHistKSigmaVsElSigma17",TheCut,"COLZ" )
fHistKSigmaVsElSigma17.SetDirectory(0)
fHistKSigmaVsElSigma17.Write()
fHistKSigmaVsElSigma27 = fHistKSigmaVsElSigma2.Clone("fHistKSigmaVsElSigma27")
SigmaK_17.cd(2)
tree.Draw("fElSigma1:fKaonSigma1>>fHistKSigmaVsElSigma27",TheCut,"COLZ" )
fHistKSigmaVsElSigma27.SetDirectory(0)
fHistKSigmaVsElSigma27.Write()
SigmaK_17.Write()

SigmaK_07 = Master_Canvas.Clone("SigmaK_07")
SigmaK_07.SetName("SigmaP_07")
SigmaK_07.Divide(2,1)
fHistKSigmaVsPSigma17 = fHistKSigmaVsPSigma1.Clone("fHistKSigmaVsPSigma17")
SigmaK_07.cd(1)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma17",TheCut,"COLZ" )
fHistKSigmaVsPSigma17.SetDirectory(0)
fHistKSigmaVsPSigma17.Write()


fHistKSigmaVsPSigma27 = fHistKSigmaVsPSigma2.Clone("fHistKSigmaVsPSigma27")
SigmaK_07.cd(2)
tree.Draw("fPiSigma0:fKaonSigma0>>fHistKSigmaVsPSigma27",TheCut,"COLZ")
fHistKSigmaVsPSigma27.SetDirectory(0)
fHistKSigmaVsPSigma27.Write()
SigmaK_07.Write()

SigmaTOF_07 = Master_Canvas.Clone("SigmaTOF_07")
SigmaTOF_07.SetName("SigmaTOF_07")
fHistKSigmaTOF7 = fHistKSigmaTOF.Clone("fHistKSigmaTOF7")
SigmaTOF_07.cd()
tree.Draw("fKaonSigmaTOF0:fKaonSigmaTOF1>>fHistKSigmaTOF7",TheCut,"COLZ")
fHistKSigmaTOF7.SetDirectory(0)
fHistKSigmaTOF7.Write()
SigmaTOF_07.Write()


SigmaTOF_17 = Master_Canvas.Clone("SigmaTOF_17")
SigmaTOF_17.SetName("SigmaTOF_17")
fHistPiSigmaTOF7 = fHistPiSigmaTOF.Clone("fHistPiSigmaTOF7")
SigmaTOF_17.cd()
tree.Draw("fPiSigmaTOF0:fPiSigmaTOF1>>fHistPiSigmaTOF7",TheCut,"COLZ")
fHistPiSigmaTOF7.SetDirectory(0)
fHistPiSigmaTOF7.Write()
SigmaTOF_17.Write()

SigmaTOF_27 = Master_Canvas.Clone("SigmaTOF_27")
SigmaTOF_27.SetName("SigmaTOF_27")
fHistElSigmaTOF7 = fHistElSigmaTOF.Clone("fHistElSigmaTOF7")
SigmaTOF_27.cd()
tree.Draw("fElSigmaTOF0:fElSigmaTOF1>>fHistElSigmaTOF7",TheCut,"COLZ")
fHistElSigmaTOF7.SetDirectory(0)
fHistElSigmaTOF7.Write()
SigmaTOF_27.Write()
    #SigmaTOFp
SigmaTOFP1_07 = Master_Canvas.Clone("SigmaTOFP1_07")
SigmaTOFP1_07.SetName("SigmaTOFP1_07")
fHistKSigmaTOFP17 = fHistKSigmaTOFP1.Clone("fHistKSigmaTOFP17")

fHistKSigmaTOFP27 = fHistKSigmaTOFP2.Clone("fHistKSigmaTOFP27")
fHistKSigmaTOFP27.SetName("fHistKSigmaTOFP27")

SigmaTOFP1_07.Divide(2,1)
SigmaTOFP1_07.cd(1)
tree.Draw("fKaonSigmaTOF0:fPd0>>fHistKSigmaTOFP17",TheCut,"COLZ")
fHistKSigmaTOFP17.SetDirectory(0)
SigmaTOFP1_07.cd(2)
tree.Draw("fKaonSigmaTOF1:fPd1>>fHistKSigmaTOFP27",TheCut,"COLZ")
fHistKSigmaTOFP27.SetDirectory(0)
fHistKSigmaTOFP17.Write()
fHistKSigmaTOFP27.Write()
SigmaTOFP1_07.Write()

SigmaTOFP_17 = Master_Canvas.Clone("SigmaTOFP_17")
SigmaTOFP_17.SetName("SigmaTOFP_17")
fHistPiSigmaTOFP17 = fHistPiSigmaTOFP1.Clone("fHistPiSigmaTOFP17")
fHistPiSigmaTOFP27 = fHistPiSigmaTOFP2.Clone("fHistPiSigmaTOFP27")
SigmaTOFP_17.Divide(2,1)
SigmaTOFP_17.cd(1)
tree.Draw("fPiSigmaTOF0:fPd0>>fHistPiSigmaTOFP17",TheCut,"COLZ")
fHistPiSigmaTOFP17.SetDirectory(0)

SigmaTOFP_17.cd(2)
tree.Draw("fPiSigmaTOF1:fPd1>>fHistPiSigmaTOFP27",TheCut,"COLZ")
fHistPiSigmaTOFP27.SetDirectory(0)
fHistPiSigmaTOFP17.Write()
fHistPiSigmaTOFP27.Write()
SigmaTOFP_17.Write()

SigmaTOFP_27 = Master_Canvas.Clone("SigmaTOFP_27")
SigmaTOFP_27.SetName("SigmaTOFP_27")
fHistElSigmaTOFP17 = fHistElSigmaTOFP1.Clone("fHistElSigmaTOFP17")
fHistElSigmaTOFP27 = fHistElSigmaTOFP2.Clone("fHistElSigmaTOFP27")

SigmaTOFP_27.Divide(2,1)
SigmaTOFP_27.cd(1)
tree.Draw("fElSigmaTOF0:fPd0>>fHistElSigmaTOFP17",TheCut,"COLZ")
fHistElSigmaTOFP17.SetDirectory(0)   
SigmaTOFP_27.cd(2)
tree.Draw("fElSigmaTOF1:fPd1>>fHistElSigmaTOFP27",TheCut,"COLZ")
fHistElSigmaTOFP27.SetDirectory(0)
fHistElSigmaTOFP17.Write()
fHistElSigmaTOFP27.Write()
SigmaTOFP_27.Write()

    #SigmaTOFof kaon vs el or p
SigmaTOFK_07 = Master_Canvas.Clone("SigmaTOFK_07")
SigmaTOFK_07.SetName("SigmaTOFK_07")
fHistKSigmaTOFVsPSigmaTOF17 = fHistKSigmaTOFVsPSigmaTOF1.Clone("fHistKSigmaTOFVsPSigmaTOF17")

fHistKSigmaTOFVsPSigmaTOF27 = fHistKSigmaTOFVsPSigmaTOF2.Clone("fHistKSigmaTOFVsPSigmaTOF27")
SigmaTOFK_07.Divide(2,1)
SigmaTOFK_07.cd(1)  
tree.Draw("fPiSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsPSigmaTOF17",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF17.SetDirectory(0)
SigmaTOFK_07.cd(2)  
tree.Draw("fPiSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsPSigmaTOF27",TheCut,"COLZ")
fHistKSigmaTOFVsPSigmaTOF27.SetDirectory(0)
fHistKSigmaTOFVsPSigmaTOF17.Write()
fHistKSigmaTOFVsPSigmaTOF27.Write()
SigmaTOFK_07.Write()

SigmaTOFK_17 = Master_Canvas.Clone("SigmaTOFK_17")
SigmaTOFK_17.SetName("SigmaTOFK_17")
fHistKSigmaTOFVsElSigmaTOF17 = fHistKSigmaTOFVsElSigmaTOF1.Clone("fHistKSigmaTOFVsElSigmaTOF17")
fHistKSigmaTOFVsElSigmaTOF27 = fHistKSigmaTOFVsElSigmaTOF2.Clone("fHistKSigmaTOFVsElSigmaTOF27")

SigmaTOFK_17.Divide(2,1)
SigmaTOFK_17.cd(1)  
tree.Draw("fElSigmaTOF0:fKaonSigmaTOF0>>fHistKSigmaTOFVsElSigmaTOF17",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF17.SetDirectory(0)
SigmaTOFK_17.cd(2)  
tree.Draw("fElSigmaTOF1:fKaonSigmaTOF1>>fHistKSigmaTOFVsElSigmaTOF27",TheCut,"COLZ")
fHistKSigmaTOFVsElSigmaTOF27.SetDirectory(0)
fHistKSigmaTOFVsElSigmaTOF17.Write()
fHistKSigmaTOFVsElSigmaTOF27.Write()
SigmaTOFK_17.Write()

# multiple folder can be added here
file2.Write()
#tree.delete()
file2.Close()

# Mass

#The lines below are so that pyroot do not exit on completing the analysis
vars = globals()
vars.update(locals())
shell = code.InteractiveConsole(vars)
shell.interact()


